// QUERY: StaffingData (SharePoint list connection)
// Paste this into: Home > Transform Data > New Source > Blank Query > Advanced Editor
// PREREQUISITE: Create the SharePointSiteURL parameter first (see 01_SharePointSiteURL_Parameter.m)

let
    Source = SharePoint.Tables(SharePointSiteURL, [Implementation="2.0", ApiVersion=15]),
    StaffingMatrix = Source{[Title="StaffingMatrix"]}[Items],
    #"Selected Columns" = Table.SelectColumns(StaffingMatrix, {"Timestamp", "Date", "TimeEntryDate", "TotalStaffedBeds", "TotalCensus", "OccupancyPct", "Census_1East", "OccPct_1East", "Census_2East", "OccPct_2East", "Census_2West", "OccPct_2West", "Census_3East", "OccPct_3East", "Census_3West", "OccPct_3West", "Census_HRC", "OccPct_HRC", "ObsHrs_Total", "ObsHrs_1East", "ObsHrs_2East", "ObsHrs_2West", "ObsHrs_3East", "ObsHrs_3West", "ObsHrs_HRC", "NP_ModelPct", "NP_Multiplier", "NP_1East", "NP_2East", "NP_2West", "NP_3East", "NP_3West", "NP_HRC", "1East_Day_RN", "1East_Day_LPN", "1East_Day_Tech", "1East_Evening_RN", "1East_Evening_LPN", "1East_Evening_Tech", "1East_Night_RN", "1East_Night_LPN", "1East_Night_Tech", "1East_ShiftTotal", "1East_Ratio_Day", "1East_Ratio_Eve", "1East_Ratio_Night", "2East_Day_RN", "2East_Day_LPN", "2East_Day_Tech", "2East_Evening_RN", "2East_Evening_LPN", "2East_Evening_Tech", "2East_Night_RN", "2East_Night_LPN", "2East_Night_Tech", "2East_ShiftTotal", "2East_Ratio_Day", "2East_Ratio_Eve", "2East_Ratio_Night", "2West_Day_RN", "2West_Day_LPN", "2West_Day_Tech", "2West_Evening_RN", "2West_Evening_LPN", "2West_Evening_Tech", "2West_Night_RN", "2West_Night_LPN", "2West_Night_Tech", "2West_ShiftTotal", "2West_Ratio_Day", "2West_Ratio_Eve", "2West_Ratio_Night", "3East_Day_RN", "3East_Day_LPN", "3East_Day_Tech", "3East_Evening_RN", "3East_Evening_LPN", "3East_Evening_Tech", "3East_Night_RN", "3East_Night_LPN", "3East_Night_Tech", "3East_ShiftTotal", "3East_Ratio_Day", "3East_Ratio_Eve", "3East_Ratio_Night", "3West_Day_RN", "3West_Day_LPN", "3West_Day_Tech", "3West_Evening_RN", "3West_Evening_LPN", "3West_Evening_Tech", "3West_Night_RN", "3West_Night_LPN", "3West_Night_Tech", "3West_ShiftTotal", "3West_Ratio_Day", "3West_Ratio_Eve", "3West_Ratio_Night", "HRC_Day_RN", "HRC_Day_LPN", "HRC_Day_Tech", "HRC_Evening_RN", "HRC_Evening_LPN", "HRC_Evening_Tech", "HRC_Night_RN", "HRC_Night_LPN", "HRC_Night_Tech", "HRC_ShiftTotal", "HRC_Ratio_Day", "HRC_Ratio_Eve", "HRC_Ratio_Night", "Total_RN", "Total_LPN", "Total_Tech", "Total_ShiftStaff", "StaffPerShift", "FloatShiftPositions", "RN_ProdFTE", "RN_AdjFTE", "LPN_ProdFTE", "LPN_AdjFTE", "Tech_ProdFTE", "Tech_AdjFTE", "Float_ProdFTE", "Float_AdjFTE", "OneOne_ProdFTE", "OneOne_AdjFTE", "VarProdFTE", "VarAdjFTE", "VarNP_Add", "FixedFTE", "FixedHC", "FixedSource", "GrandProdFTE", "GrandAdjFTE", "EPOB_DirectCare", "EPOB_TotalFacility", "EPOB_Productive", "EPOB_VarPerPatient", "EPOB_FixPerPatient", "HasPayrollData", "PayrollFileName", "PayrollDayCount", "PayrollStartDate", "PayrollEndDate", "Actual_HrsDay_1East", "Actual_HC_1East", "Actual_OT_1East", "Actual_NpHrs_1East", "Actual_Wages_1East", "Model_HrsDay_1East", "Variance_HrsDay_1East", "Variance_Pct_1East", "Actual_HrsDay_2East", "Actual_HC_2East", "Actual_OT_2East", "Actual_NpHrs_2East", "Actual_Wages_2East", "Model_HrsDay_2East", "Variance_HrsDay_2East", "Variance_Pct_2East", "Actual_HrsDay_2West", "Actual_HC_2West", "Actual_OT_2West", "Actual_NpHrs_2West", "Actual_Wages_2West", "Model_HrsDay_2West", "Variance_HrsDay_2West", "Variance_Pct_2West", "Actual_HrsDay_3East", "Actual_HC_3East", "Actual_OT_3East", "Actual_NpHrs_3East", "Actual_Wages_3East", "Model_HrsDay_3East", "Variance_HrsDay_3East", "Variance_Pct_3East", "Actual_HrsDay_3West", "Actual_HC_3West", "Actual_OT_3West", "Actual_NpHrs_3West", "Actual_Wages_3West", "Model_HrsDay_3West", "Variance_HrsDay_3West", "Variance_Pct_3West", "Actual_HrsDay_HRC", "Actual_HC_HRC", "Actual_OT_HRC", "Actual_NpHrs_HRC", "Actual_Wages_HRC", "Model_HrsDay_HRC", "Variance_HrsDay_HRC", "Variance_Pct_HRC", "Actual_VarHrsDay_Total", "Actual_FixHrsDay_Total", "Actual_VarHC_Total", "Actual_FixHC_Total", "Actual_OT_Total", "Model_VarHrsDay_Total", "Variance_VarHrsDay_Total", "Variance_VarPct_Total", "Actual_VarFTE", "Actual_FixFTE", "Actual_TotalFTE", "Actual_EPOB_DC", "Actual_EPOB_Total", "EPOB_DC_Variance", "EPOB_Total_Variance"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Selected Columns", {
        {"Timestamp", type text},
        {"Date", type text},
        {"TimeEntryDate", type text},
        {"TotalStaffedBeds", type number},
        {"TotalCensus", type number},
        {"OccupancyPct", type number},
        {"Census_1East", type number},
        {"OccPct_1East", type number},
        {"Census_2East", type number},
        {"OccPct_2East", type number},
        {"Census_2West", type number},
        {"OccPct_2West", type number},
        {"Census_3East", type number},
        {"OccPct_3East", type number},
        {"Census_3West", type number},
        {"OccPct_3West", type number},
        {"Census_HRC", type number},
        {"OccPct_HRC", type number},
        {"ObsHrs_Total", type number},
        {"ObsHrs_1East", type number},
        {"ObsHrs_2East", type number},
        {"ObsHrs_2West", type number},
        {"ObsHrs_3East", type number},
        {"ObsHrs_3West", type number},
        {"ObsHrs_HRC", type number},
        {"NP_ModelPct", type number},
        {"NP_Multiplier", type number},
        {"NP_1East", type number},
        {"NP_2East", type number},
        {"NP_2West", type number},
        {"NP_3East", type number},
        {"NP_3West", type number},
        {"NP_HRC", type number},
        {"1East_Day_RN", type number},
        {"1East_Day_LPN", type number},
        {"1East_Day_Tech", type number},
        {"1East_Evening_RN", type number},
        {"1East_Evening_LPN", type number},
        {"1East_Evening_Tech", type number},
        {"1East_Night_RN", type number},
        {"1East_Night_LPN", type number},
        {"1East_Night_Tech", type number},
        {"1East_ShiftTotal", type number},
        {"1East_Ratio_Day", type number},
        {"1East_Ratio_Eve", type number},
        {"1East_Ratio_Night", type number},
        {"2East_Day_RN", type number},
        {"2East_Day_LPN", type number},
        {"2East_Day_Tech", type number},
        {"2East_Evening_RN", type number},
        {"2East_Evening_LPN", type number},
        {"2East_Evening_Tech", type number},
        {"2East_Night_RN", type number},
        {"2East_Night_LPN", type number},
        {"2East_Night_Tech", type number},
        {"2East_ShiftTotal", type number},
        {"2East_Ratio_Day", type number},
        {"2East_Ratio_Eve", type number},
        {"2East_Ratio_Night", type number},
        {"2West_Day_RN", type number},
        {"2West_Day_LPN", type number},
        {"2West_Day_Tech", type number},
        {"2West_Evening_RN", type number},
        {"2West_Evening_LPN", type number},
        {"2West_Evening_Tech", type number},
        {"2West_Night_RN", type number},
        {"2West_Night_LPN", type number},
        {"2West_Night_Tech", type number},
        {"2West_ShiftTotal", type number},
        {"2West_Ratio_Day", type number},
        {"2West_Ratio_Eve", type number},
        {"2West_Ratio_Night", type number},
        {"3East_Day_RN", type number},
        {"3East_Day_LPN", type number},
        {"3East_Day_Tech", type number},
        {"3East_Evening_RN", type number},
        {"3East_Evening_LPN", type number},
        {"3East_Evening_Tech", type number},
        {"3East_Night_RN", type number},
        {"3East_Night_LPN", type number},
        {"3East_Night_Tech", type number},
        {"3East_ShiftTotal", type number},
        {"3East_Ratio_Day", type number},
        {"3East_Ratio_Eve", type number},
        {"3East_Ratio_Night", type number},
        {"3West_Day_RN", type number},
        {"3West_Day_LPN", type number},
        {"3West_Day_Tech", type number},
        {"3West_Evening_RN", type number},
        {"3West_Evening_LPN", type number},
        {"3West_Evening_Tech", type number},
        {"3West_Night_RN", type number},
        {"3West_Night_LPN", type number},
        {"3West_Night_Tech", type number},
        {"3West_ShiftTotal", type number},
        {"3West_Ratio_Day", type number},
        {"3West_Ratio_Eve", type number},
        {"3West_Ratio_Night", type number},
        {"HRC_Day_RN", type number},
        {"HRC_Day_LPN", type number},
        {"HRC_Day_Tech", type number},
        {"HRC_Evening_RN", type number},
        {"HRC_Evening_LPN", type number},
        {"HRC_Evening_Tech", type number},
        {"HRC_Night_RN", type number},
        {"HRC_Night_LPN", type number},
        {"HRC_Night_Tech", type number},
        {"HRC_ShiftTotal", type number},
        {"HRC_Ratio_Day", type number},
        {"HRC_Ratio_Eve", type number},
        {"HRC_Ratio_Night", type number},
        {"Total_RN", type number},
        {"Total_LPN", type number},
        {"Total_Tech", type number},
        {"Total_ShiftStaff", type number},
        {"StaffPerShift", type number},
        {"FloatShiftPositions", type number},
        {"RN_ProdFTE", type number},
        {"RN_AdjFTE", type number},
        {"LPN_ProdFTE", type number},
        {"LPN_AdjFTE", type number},
        {"Tech_ProdFTE", type number},
        {"Tech_AdjFTE", type number},
        {"Float_ProdFTE", type number},
        {"Float_AdjFTE", type number},
        {"OneOne_ProdFTE", type number},
        {"OneOne_AdjFTE", type number},
        {"VarProdFTE", type number},
        {"VarAdjFTE", type number},
        {"VarNP_Add", type number},
        {"FixedFTE", type number},
        {"FixedHC", type number},
        {"FixedSource", type text},
        {"GrandProdFTE", type number},
        {"GrandAdjFTE", type number},
        {"EPOB_DirectCare", type number},
        {"EPOB_TotalFacility", type number},
        {"EPOB_Productive", type number},
        {"EPOB_VarPerPatient", type number},
        {"EPOB_FixPerPatient", type number},
        {"HasPayrollData", type logical},
        {"PayrollFileName", type text},
        {"PayrollDayCount", type number},
        {"PayrollStartDate", type text},
        {"PayrollEndDate", type text},
        {"Actual_HrsDay_1East", type number},
        {"Actual_HC_1East", type number},
        {"Actual_OT_1East", type number},
        {"Actual_NpHrs_1East", type number},
        {"Actual_Wages_1East", type number},
        {"Model_HrsDay_1East", type number},
        {"Variance_HrsDay_1East", type number},
        {"Variance_Pct_1East", type number},
        {"Actual_HrsDay_2East", type number},
        {"Actual_HC_2East", type number},
        {"Actual_OT_2East", type number},
        {"Actual_NpHrs_2East", type number},
        {"Actual_Wages_2East", type number},
        {"Model_HrsDay_2East", type number},
        {"Variance_HrsDay_2East", type number},
        {"Variance_Pct_2East", type number},
        {"Actual_HrsDay_2West", type number},
        {"Actual_HC_2West", type number},
        {"Actual_OT_2West", type number},
        {"Actual_NpHrs_2West", type number},
        {"Actual_Wages_2West", type number},
        {"Model_HrsDay_2West", type number},
        {"Variance_HrsDay_2West", type number},
        {"Variance_Pct_2West", type number},
        {"Actual_HrsDay_3East", type number},
        {"Actual_HC_3East", type number},
        {"Actual_OT_3East", type number},
        {"Actual_NpHrs_3East", type number},
        {"Actual_Wages_3East", type number},
        {"Model_HrsDay_3East", type number},
        {"Variance_HrsDay_3East", type number},
        {"Variance_Pct_3East", type number},
        {"Actual_HrsDay_3West", type number},
        {"Actual_HC_3West", type number},
        {"Actual_OT_3West", type number},
        {"Actual_NpHrs_3West", type number},
        {"Actual_Wages_3West", type number},
        {"Model_HrsDay_3West", type number},
        {"Variance_HrsDay_3West", type number},
        {"Variance_Pct_3West", type number},
        {"Actual_HrsDay_HRC", type number},
        {"Actual_HC_HRC", type number},
        {"Actual_OT_HRC", type number},
        {"Actual_NpHrs_HRC", type number},
        {"Actual_Wages_HRC", type number},
        {"Model_HrsDay_HRC", type number},
        {"Variance_HrsDay_HRC", type number},
        {"Variance_Pct_HRC", type number},
        {"Actual_VarHrsDay_Total", type number},
        {"Actual_FixHrsDay_Total", type number},
        {"Actual_VarHC_Total", type number},
        {"Actual_FixHC_Total", type number},
        {"Actual_OT_Total", type number},
        {"Model_VarHrsDay_Total", type number},
        {"Variance_VarHrsDay_Total", type number},
        {"Variance_VarPct_Total", type number},
        {"Actual_VarFTE", type number},
        {"Actual_FixFTE", type number},
        {"Actual_TotalFTE", type number},
        {"Actual_EPOB_DC", type number},
        {"Actual_EPOB_Total", type number},
        {"EPOB_DC_Variance", type number},
        {"EPOB_Total_Variance", type number}
    }),
    // TimeEntryDate is the actual census/payroll date (e.g. "2026-03-15")
    // Date is just when the record was pushed to SharePoint
    #"Added TimeEntryDateKey" = Table.AddColumn(#"Changed Type", "TimeEntryDateKey", each
        try Date.FromText([TimeEntryDate]) otherwise null, type date),
    #"Added SubmitDateKey" = Table.AddColumn(#"Added TimeEntryDateKey", "SubmitDateKey", each
        try Date.From([Date]) otherwise null, type date)
in
    #"Added SubmitDateKey"
