// ============================================================================
// HIGHLAND STAFFING MATRIX — DAX MEASURES
// ============================================================================
// DASHBOARDS: Daily | Monthly | YTD — each in Total + by Unit
//
// SETUP: First create the DateTable (04_DateTable.dax) and relationship:
//   DateTable[Date] → StaffingData[TimeEntryDateKey]  (one-to-many, cross-filter: Both)
//
// NOTE: TimeEntryDate = the actual census/payroll date being reported
//       Date = when the record was pushed to SharePoint (not what you want)
//
// HOW TO ADD: Select StaffingData table > Modeling > New Measure > paste formula
// To set Display Folder: Select measure > Properties > Display Folder
// ============================================================================


// ════════════════════════════════════════════════════════════════════════════
//  DAILY DASHBOARD MEASURES
//  (Show the selected day's snapshot — use with a single-date slicer)
// ════════════════════════════════════════════════════════════════════════════

// ── Daily: Facility Total ─────────────────────────────────────────────────

Daily Total Census = SUM(StaffingData[TotalCensus])
// Format: #,0  |  Display Folder: Daily - Facility

Daily Occupancy % = DIVIDE(SUM(StaffingData[TotalCensus]), 114, 0) * 100
// Format: 0.0  |  Display Folder: Daily - Facility

Daily Total RN = SUM(StaffingData[Total_RN])
// Format: #,0  |  Display Folder: Daily - Facility

Daily Total LPN = SUM(StaffingData[Total_LPN])
// Format: #,0  |  Display Folder: Daily - Facility

Daily Total Tech = SUM(StaffingData[Total_Tech])
// Format: #,0  |  Display Folder: Daily - Facility

Daily Total Shift Staff = SUM(StaffingData[Total_ShiftStaff])
// Format: #,0  |  Display Folder: Daily - Facility

Daily DC EPOB = AVERAGE(StaffingData[EPOB_DirectCare])
// Format: 0.00  |  Display Folder: Daily - Facility

Daily Total EPOB = AVERAGE(StaffingData[EPOB_TotalFacility])
// Format: 0.00  |  Display Folder: Daily - Facility

Daily Variable FTE = SUM(StaffingData[VarAdjFTE])
// Format: 0.0  |  Display Folder: Daily - Facility

Daily Fixed FTE = SUM(StaffingData[FixedFTE])
// Format: 0.0  |  Display Folder: Daily - Facility

Daily Grand FTE = SUM(StaffingData[GrandAdjFTE])
// Format: 0.0  |  Display Folder: Daily - Facility

Daily RN FTE = SUM(StaffingData[RN_AdjFTE])
// Format: 0.0  |  Display Folder: Daily - Facility

Daily LPN FTE = SUM(StaffingData[LPN_AdjFTE])
// Format: 0.0  |  Display Folder: Daily - Facility

Daily Tech FTE = SUM(StaffingData[Tech_AdjFTE])
// Format: 0.0  |  Display Folder: Daily - Facility

Daily Float Positions = SUM(StaffingData[FloatShiftPositions])
// Format: #,0  |  Display Folder: Daily - Facility

Daily Obs Hours = SUM(StaffingData[ObsHrs_Total])
// Format: 0.0  |  Display Folder: Daily - Facility

Daily NP Model % = AVERAGE(StaffingData[NP_ModelPct])
// Format: 0.0  |  Display Folder: Daily - Facility

Daily Actual Hours = SUM(StaffingData[Actual_VarHrsDay_Total])
// Format: 0.0  |  Display Folder: Daily - Facility

Daily Model Hours = SUM(StaffingData[Model_VarHrsDay_Total])
// Format: 0.0  |  Display Folder: Daily - Facility

Daily Hours Variance = SUM(StaffingData[Variance_VarHrsDay_Total])
// Format: +0.0;-0.0;0.0  |  Display Folder: Daily - Facility

Daily Variance % = AVERAGE(StaffingData[Variance_VarPct_Total])
// Format: +0.0;-0.0;0.0  |  Display Folder: Daily - Facility

Daily OT Hours = SUM(StaffingData[Actual_OT_Total])
// Format: 0.0  |  Display Folder: Daily - Facility

Daily Actual DC EPOB = AVERAGE(StaffingData[Actual_EPOB_DC])
// Format: 0.00  |  Display Folder: Daily - Facility

Daily Actual Total EPOB = AVERAGE(StaffingData[Actual_EPOB_Total])
// Format: 0.00  |  Display Folder: Daily - Facility

Daily EPOB DC Variance = AVERAGE(StaffingData[EPOB_DC_Variance])
// Format: +0.00;-0.00;0.00  |  Display Folder: Daily - Facility

Daily EPOB Total Variance = AVERAGE(StaffingData[EPOB_Total_Variance])
// Format: +0.00;-0.00;0.00  |  Display Folder: Daily - Facility


// ── Daily: By Unit (Census) ───────────────────────────────────────────────

Daily Census 1East = SUM(StaffingData[Census_1East])
// Format: #,0  |  Display Folder: Daily - By Unit

Daily Census 2East = SUM(StaffingData[Census_2East])
// Format: #,0  |  Display Folder: Daily - By Unit

Daily Census 2West = SUM(StaffingData[Census_2West])
// Format: #,0  |  Display Folder: Daily - By Unit

Daily Census 3East = SUM(StaffingData[Census_3East])
// Format: #,0  |  Display Folder: Daily - By Unit

Daily Census 3West = SUM(StaffingData[Census_3West])
// Format: #,0  |  Display Folder: Daily - By Unit

Daily Census HRC = SUM(StaffingData[Census_HRC])
// Format: #,0  |  Display Folder: Daily - By Unit

Daily Occ% 1East = DIVIDE(SUM(StaffingData[Census_1East]), 18, 0) * 100
// Format: 0.0  |  Display Folder: Daily - By Unit

Daily Occ% 2East = DIVIDE(SUM(StaffingData[Census_2East]), 20, 0) * 100
// Format: 0.0  |  Display Folder: Daily - By Unit

Daily Occ% 2West = DIVIDE(SUM(StaffingData[Census_2West]), 20, 0) * 100
// Format: 0.0  |  Display Folder: Daily - By Unit

Daily Occ% 3East = DIVIDE(SUM(StaffingData[Census_3East]), 20, 0) * 100
// Format: 0.0  |  Display Folder: Daily - By Unit

Daily Occ% 3West = DIVIDE(SUM(StaffingData[Census_3West]), 20, 0) * 100
// Format: 0.0  |  Display Folder: Daily - By Unit

Daily Occ% HRC = DIVIDE(SUM(StaffingData[Census_HRC]), 16, 0) * 100
// Format: 0.0  |  Display Folder: Daily - By Unit


// ── Daily: By Unit (Staffing & Variance) ──────────────────────────────────

Daily Staff 1East = SUM(StaffingData[1East_ShiftTotal])
// Format: #,0  |  Display Folder: Daily - By Unit

Daily Staff 2East = SUM(StaffingData[2East_ShiftTotal])
// Format: #,0  |  Display Folder: Daily - By Unit

Daily Staff 2West = SUM(StaffingData[2West_ShiftTotal])
// Format: #,0  |  Display Folder: Daily - By Unit

Daily Staff 3East = SUM(StaffingData[3East_ShiftTotal])
// Format: #,0  |  Display Folder: Daily - By Unit

Daily Staff 3West = SUM(StaffingData[3West_ShiftTotal])
// Format: #,0  |  Display Folder: Daily - By Unit

Daily Staff HRC = SUM(StaffingData[HRC_ShiftTotal])
// Format: #,0  |  Display Folder: Daily - By Unit

Daily Var Hrs 1East = SUM(StaffingData[Variance_HrsDay_1East])
// Format: +0.0;-0.0;0.0  |  Display Folder: Daily - By Unit

Daily Var Hrs 2East = SUM(StaffingData[Variance_HrsDay_2East])
// Format: +0.0;-0.0;0.0  |  Display Folder: Daily - By Unit

Daily Var Hrs 2West = SUM(StaffingData[Variance_HrsDay_2West])
// Format: +0.0;-0.0;0.0  |  Display Folder: Daily - By Unit

Daily Var Hrs 3East = SUM(StaffingData[Variance_HrsDay_3East])
// Format: +0.0;-0.0;0.0  |  Display Folder: Daily - By Unit

Daily Var Hrs 3West = SUM(StaffingData[Variance_HrsDay_3West])
// Format: +0.0;-0.0;0.0  |  Display Folder: Daily - By Unit

Daily Var Hrs HRC = SUM(StaffingData[Variance_HrsDay_HRC])
// Format: +0.0;-0.0;0.0  |  Display Folder: Daily - By Unit

Daily OT 1East = SUM(StaffingData[Actual_OT_1East])
// Format: 0.0  |  Display Folder: Daily - By Unit

Daily OT 2East = SUM(StaffingData[Actual_OT_2East])
// Format: 0.0  |  Display Folder: Daily - By Unit

Daily OT 2West = SUM(StaffingData[Actual_OT_2West])
// Format: 0.0  |  Display Folder: Daily - By Unit

Daily OT 3East = SUM(StaffingData[Actual_OT_3East])
// Format: 0.0  |  Display Folder: Daily - By Unit

Daily OT 3West = SUM(StaffingData[Actual_OT_3West])
// Format: 0.0  |  Display Folder: Daily - By Unit

Daily OT HRC = SUM(StaffingData[Actual_OT_HRC])
// Format: 0.0  |  Display Folder: Daily - By Unit


// ════════════════════════════════════════════════════════════════════════════
//  MTD (MONTHLY) DASHBOARD MEASURES
//  (Averages & totals from 1st of selected month through last data point)
//  These respond to the date slicer — select any date in the target month
// ════════════════════════════════════════════════════════════════════════════

// ── MTD: Facility Total ──────────────────────────────────────────────────

MTD Avg Daily Census =
VAR _monthStart = DATE(YEAR(MIN(DateTable[Date])), MONTH(MIN(DateTable[Date])), 1)
VAR _monthEnd = EOMONTH(_monthStart, 0)
RETURN
    CALCULATE(
        AVERAGE(StaffingData[TotalCensus]),
        FILTER(ALL(DateTable), DateTable[Date] >= _monthStart && DateTable[Date] <= _monthEnd)
    )
// Format: 0.0  |  Display Folder: MTD - Facility

MTD Avg Occupancy % = DIVIDE([MTD Avg Daily Census], 114, 0) * 100
// Format: 0.0  |  Display Folder: MTD - Facility

MTD Avg DC EPOB =
VAR _monthStart = DATE(YEAR(MIN(DateTable[Date])), MONTH(MIN(DateTable[Date])), 1)
VAR _monthEnd = EOMONTH(_monthStart, 0)
RETURN
    CALCULATE(
        AVERAGE(StaffingData[EPOB_DirectCare]),
        FILTER(ALL(DateTable), DateTable[Date] >= _monthStart && DateTable[Date] <= _monthEnd)
    )
// Format: 0.00  |  Display Folder: MTD - Facility

MTD Avg Total EPOB =
VAR _monthStart = DATE(YEAR(MIN(DateTable[Date])), MONTH(MIN(DateTable[Date])), 1)
VAR _monthEnd = EOMONTH(_monthStart, 0)
RETURN
    CALCULATE(
        AVERAGE(StaffingData[EPOB_TotalFacility]),
        FILTER(ALL(DateTable), DateTable[Date] >= _monthStart && DateTable[Date] <= _monthEnd)
    )
// Format: 0.00  |  Display Folder: MTD - Facility

MTD Avg Variable FTE =
VAR _monthStart = DATE(YEAR(MIN(DateTable[Date])), MONTH(MIN(DateTable[Date])), 1)
VAR _monthEnd = EOMONTH(_monthStart, 0)
RETURN
    CALCULATE(
        AVERAGE(StaffingData[VarAdjFTE]),
        FILTER(ALL(DateTable), DateTable[Date] >= _monthStart && DateTable[Date] <= _monthEnd)
    )
// Format: 0.0  |  Display Folder: MTD - Facility

MTD Avg Fixed FTE =
VAR _monthStart = DATE(YEAR(MIN(DateTable[Date])), MONTH(MIN(DateTable[Date])), 1)
VAR _monthEnd = EOMONTH(_monthStart, 0)
RETURN
    CALCULATE(
        AVERAGE(StaffingData[FixedFTE]),
        FILTER(ALL(DateTable), DateTable[Date] >= _monthStart && DateTable[Date] <= _monthEnd)
    )
// Format: 0.0  |  Display Folder: MTD - Facility

MTD Avg Grand FTE =
VAR _monthStart = DATE(YEAR(MIN(DateTable[Date])), MONTH(MIN(DateTable[Date])), 1)
VAR _monthEnd = EOMONTH(_monthStart, 0)
RETURN
    CALCULATE(
        AVERAGE(StaffingData[GrandAdjFTE]),
        FILTER(ALL(DateTable), DateTable[Date] >= _monthStart && DateTable[Date] <= _monthEnd)
    )
// Format: 0.0  |  Display Folder: MTD - Facility

MTD Avg Total Staff =
VAR _monthStart = DATE(YEAR(MIN(DateTable[Date])), MONTH(MIN(DateTable[Date])), 1)
VAR _monthEnd = EOMONTH(_monthStart, 0)
RETURN
    CALCULATE(
        AVERAGE(StaffingData[Total_ShiftStaff]),
        FILTER(ALL(DateTable), DateTable[Date] >= _monthStart && DateTable[Date] <= _monthEnd)
    )
// Format: 0.0  |  Display Folder: MTD - Facility

MTD Avg RN =
VAR _monthStart = DATE(YEAR(MIN(DateTable[Date])), MONTH(MIN(DateTable[Date])), 1)
VAR _monthEnd = EOMONTH(_monthStart, 0)
RETURN
    CALCULATE(
        AVERAGE(StaffingData[Total_RN]),
        FILTER(ALL(DateTable), DateTable[Date] >= _monthStart && DateTable[Date] <= _monthEnd)
    )
// Format: 0.0  |  Display Folder: MTD - Facility

MTD Avg LPN =
VAR _monthStart = DATE(YEAR(MIN(DateTable[Date])), MONTH(MIN(DateTable[Date])), 1)
VAR _monthEnd = EOMONTH(_monthStart, 0)
RETURN
    CALCULATE(
        AVERAGE(StaffingData[Total_LPN]),
        FILTER(ALL(DateTable), DateTable[Date] >= _monthStart && DateTable[Date] <= _monthEnd)
    )
// Format: 0.0  |  Display Folder: MTD - Facility

MTD Avg Tech =
VAR _monthStart = DATE(YEAR(MIN(DateTable[Date])), MONTH(MIN(DateTable[Date])), 1)
VAR _monthEnd = EOMONTH(_monthStart, 0)
RETURN
    CALCULATE(
        AVERAGE(StaffingData[Total_Tech]),
        FILTER(ALL(DateTable), DateTable[Date] >= _monthStart && DateTable[Date] <= _monthEnd)
    )
// Format: 0.0  |  Display Folder: MTD - Facility

MTD Total OT Hours =
VAR _monthStart = DATE(YEAR(MIN(DateTable[Date])), MONTH(MIN(DateTable[Date])), 1)
VAR _monthEnd = EOMONTH(_monthStart, 0)
RETURN
    CALCULATE(
        SUM(StaffingData[Actual_OT_Total]),
        FILTER(ALL(DateTable), DateTable[Date] >= _monthStart && DateTable[Date] <= _monthEnd)
    )
// Format: 0.0  |  Display Folder: MTD - Facility

MTD Avg Hours Variance =
VAR _monthStart = DATE(YEAR(MIN(DateTable[Date])), MONTH(MIN(DateTable[Date])), 1)
VAR _monthEnd = EOMONTH(_monthStart, 0)
RETURN
    CALCULATE(
        AVERAGE(StaffingData[Variance_VarHrsDay_Total]),
        FILTER(ALL(DateTable), DateTable[Date] >= _monthStart && DateTable[Date] <= _monthEnd)
    )
// Format: +0.0;-0.0;0.0  |  Display Folder: MTD - Facility

MTD Avg Variance % =
VAR _monthStart = DATE(YEAR(MIN(DateTable[Date])), MONTH(MIN(DateTable[Date])), 1)
VAR _monthEnd = EOMONTH(_monthStart, 0)
RETURN
    CALCULATE(
        AVERAGE(StaffingData[Variance_VarPct_Total]),
        FILTER(ALL(DateTable), DateTable[Date] >= _monthStart && DateTable[Date] <= _monthEnd)
    )
// Format: +0.0;-0.0;0.0  |  Display Folder: MTD - Facility

MTD Days Count =
VAR _monthStart = DATE(YEAR(MIN(DateTable[Date])), MONTH(MIN(DateTable[Date])), 1)
VAR _monthEnd = EOMONTH(_monthStart, 0)
RETURN
    CALCULATE(
        COUNTROWS(StaffingData),
        FILTER(ALL(DateTable), DateTable[Date] >= _monthStart && DateTable[Date] <= _monthEnd)
    )
// Format: #,0  |  Display Folder: MTD - Facility


// ── MTD: By Unit (Avg Daily Census) ──────────────────────────────────────

MTD Avg Census 1East =
VAR _monthStart = DATE(YEAR(MIN(DateTable[Date])), MONTH(MIN(DateTable[Date])), 1)
VAR _monthEnd = EOMONTH(_monthStart, 0)
RETURN
    CALCULATE(AVERAGE(StaffingData[Census_1East]), FILTER(ALL(DateTable), DateTable[Date] >= _monthStart && DateTable[Date] <= _monthEnd))
// Format: 0.0  |  Display Folder: MTD - By Unit

MTD Avg Census 2East =
VAR _monthStart = DATE(YEAR(MIN(DateTable[Date])), MONTH(MIN(DateTable[Date])), 1)
VAR _monthEnd = EOMONTH(_monthStart, 0)
RETURN
    CALCULATE(AVERAGE(StaffingData[Census_2East]), FILTER(ALL(DateTable), DateTable[Date] >= _monthStart && DateTable[Date] <= _monthEnd))
// Format: 0.0  |  Display Folder: MTD - By Unit

MTD Avg Census 2West =
VAR _monthStart = DATE(YEAR(MIN(DateTable[Date])), MONTH(MIN(DateTable[Date])), 1)
VAR _monthEnd = EOMONTH(_monthStart, 0)
RETURN
    CALCULATE(AVERAGE(StaffingData[Census_2West]), FILTER(ALL(DateTable), DateTable[Date] >= _monthStart && DateTable[Date] <= _monthEnd))
// Format: 0.0  |  Display Folder: MTD - By Unit

MTD Avg Census 3East =
VAR _monthStart = DATE(YEAR(MIN(DateTable[Date])), MONTH(MIN(DateTable[Date])), 1)
VAR _monthEnd = EOMONTH(_monthStart, 0)
RETURN
    CALCULATE(AVERAGE(StaffingData[Census_3East]), FILTER(ALL(DateTable), DateTable[Date] >= _monthStart && DateTable[Date] <= _monthEnd))
// Format: 0.0  |  Display Folder: MTD - By Unit

MTD Avg Census 3West =
VAR _monthStart = DATE(YEAR(MIN(DateTable[Date])), MONTH(MIN(DateTable[Date])), 1)
VAR _monthEnd = EOMONTH(_monthStart, 0)
RETURN
    CALCULATE(AVERAGE(StaffingData[Census_3West]), FILTER(ALL(DateTable), DateTable[Date] >= _monthStart && DateTable[Date] <= _monthEnd))
// Format: 0.0  |  Display Folder: MTD - By Unit

MTD Avg Census HRC =
VAR _monthStart = DATE(YEAR(MIN(DateTable[Date])), MONTH(MIN(DateTable[Date])), 1)
VAR _monthEnd = EOMONTH(_monthStart, 0)
RETURN
    CALCULATE(AVERAGE(StaffingData[Census_HRC]), FILTER(ALL(DateTable), DateTable[Date] >= _monthStart && DateTable[Date] <= _monthEnd))
// Format: 0.0  |  Display Folder: MTD - By Unit


// ── MTD: By Unit (Occupancy %) ───────────────────────────────────────────

MTD Avg Occ% 1East = DIVIDE([MTD Avg Census 1East], 18, 0) * 100
// Format: 0.0  |  Display Folder: MTD - By Unit

MTD Avg Occ% 2East = DIVIDE([MTD Avg Census 2East], 20, 0) * 100
// Format: 0.0  |  Display Folder: MTD - By Unit

MTD Avg Occ% 2West = DIVIDE([MTD Avg Census 2West], 20, 0) * 100
// Format: 0.0  |  Display Folder: MTD - By Unit

MTD Avg Occ% 3East = DIVIDE([MTD Avg Census 3East], 20, 0) * 100
// Format: 0.0  |  Display Folder: MTD - By Unit

MTD Avg Occ% 3West = DIVIDE([MTD Avg Census 3West], 20, 0) * 100
// Format: 0.0  |  Display Folder: MTD - By Unit

MTD Avg Occ% HRC = DIVIDE([MTD Avg Census HRC], 16, 0) * 100
// Format: 0.0  |  Display Folder: MTD - By Unit


// ── MTD: By Unit (OT Hours) ─────────────────────────────────────────────

MTD OT 1East =
VAR _monthStart = DATE(YEAR(MIN(DateTable[Date])), MONTH(MIN(DateTable[Date])), 1)
VAR _monthEnd = EOMONTH(_monthStart, 0)
RETURN
    CALCULATE(SUM(StaffingData[Actual_OT_1East]), FILTER(ALL(DateTable), DateTable[Date] >= _monthStart && DateTable[Date] <= _monthEnd))
// Format: 0.0  |  Display Folder: MTD - By Unit

MTD OT 2East =
VAR _monthStart = DATE(YEAR(MIN(DateTable[Date])), MONTH(MIN(DateTable[Date])), 1)
VAR _monthEnd = EOMONTH(_monthStart, 0)
RETURN
    CALCULATE(SUM(StaffingData[Actual_OT_2East]), FILTER(ALL(DateTable), DateTable[Date] >= _monthStart && DateTable[Date] <= _monthEnd))
// Format: 0.0  |  Display Folder: MTD - By Unit

MTD OT 2West =
VAR _monthStart = DATE(YEAR(MIN(DateTable[Date])), MONTH(MIN(DateTable[Date])), 1)
VAR _monthEnd = EOMONTH(_monthStart, 0)
RETURN
    CALCULATE(SUM(StaffingData[Actual_OT_2West]), FILTER(ALL(DateTable), DateTable[Date] >= _monthStart && DateTable[Date] <= _monthEnd))
// Format: 0.0  |  Display Folder: MTD - By Unit

MTD OT 3East =
VAR _monthStart = DATE(YEAR(MIN(DateTable[Date])), MONTH(MIN(DateTable[Date])), 1)
VAR _monthEnd = EOMONTH(_monthStart, 0)
RETURN
    CALCULATE(SUM(StaffingData[Actual_OT_3East]), FILTER(ALL(DateTable), DateTable[Date] >= _monthStart && DateTable[Date] <= _monthEnd))
// Format: 0.0  |  Display Folder: MTD - By Unit

MTD OT 3West =
VAR _monthStart = DATE(YEAR(MIN(DateTable[Date])), MONTH(MIN(DateTable[Date])), 1)
VAR _monthEnd = EOMONTH(_monthStart, 0)
RETURN
    CALCULATE(SUM(StaffingData[Actual_OT_3West]), FILTER(ALL(DateTable), DateTable[Date] >= _monthStart && DateTable[Date] <= _monthEnd))
// Format: 0.0  |  Display Folder: MTD - By Unit

MTD OT HRC =
VAR _monthStart = DATE(YEAR(MIN(DateTable[Date])), MONTH(MIN(DateTable[Date])), 1)
VAR _monthEnd = EOMONTH(_monthStart, 0)
RETURN
    CALCULATE(SUM(StaffingData[Actual_OT_HRC]), FILTER(ALL(DateTable), DateTable[Date] >= _monthStart && DateTable[Date] <= _monthEnd))
// Format: 0.0  |  Display Folder: MTD - By Unit


// ── MTD: Prior Month Comparison ──────────────────────────────────────────

Prior Month Avg Census =
VAR _curMonthStart = DATE(YEAR(MIN(DateTable[Date])), MONTH(MIN(DateTable[Date])), 1)
VAR _priorMonthStart = EDATE(_curMonthStart, -1)
VAR _priorMonthEnd = _curMonthStart - 1
RETURN
    CALCULATE(
        AVERAGE(StaffingData[TotalCensus]),
        FILTER(ALL(DateTable), DateTable[Date] >= _priorMonthStart && DateTable[Date] <= _priorMonthEnd)
    )
// Format: 0.0  |  Display Folder: MTD - Comparisons

MTD vs Prior Month Census = [MTD Avg Daily Census] - [Prior Month Avg Census]
// Format: +0.0;-0.0;0.0  |  Display Folder: MTD - Comparisons

MTD vs Prior Month % = DIVIDE([MTD Avg Daily Census] - [Prior Month Avg Census], [Prior Month Avg Census], 0) * 100
// Format: +0.0;-0.0;0.0  |  Display Folder: MTD - Comparisons


// ════════════════════════════════════════════════════════════════════════════
//  YTD DASHBOARD MEASURES
//  (Averages & totals from Jan 1 of selected year through last data point)
//  These respond to the date slicer — select any date in the target year
// ════════════════════════════════════════════════════════════════════════════

// ── YTD: Facility Total ──────────────────────────────────────────────────

YTD Avg Daily Census =
VAR _yearStart = DATE(YEAR(MIN(DateTable[Date])), 1, 1)
VAR _yearEnd = DATE(YEAR(MIN(DateTable[Date])), 12, 31)
RETURN
    CALCULATE(
        AVERAGE(StaffingData[TotalCensus]),
        FILTER(ALL(DateTable), DateTable[Date] >= _yearStart && DateTable[Date] <= _yearEnd)
    )
// Format: 0.0  |  Display Folder: YTD - Facility

YTD Avg Occupancy % = DIVIDE([YTD Avg Daily Census], 114, 0) * 100
// Format: 0.0  |  Display Folder: YTD - Facility

YTD Avg DC EPOB =
VAR _yearStart = DATE(YEAR(MIN(DateTable[Date])), 1, 1)
VAR _yearEnd = DATE(YEAR(MIN(DateTable[Date])), 12, 31)
RETURN
    CALCULATE(
        AVERAGE(StaffingData[EPOB_DirectCare]),
        FILTER(ALL(DateTable), DateTable[Date] >= _yearStart && DateTable[Date] <= _yearEnd)
    )
// Format: 0.00  |  Display Folder: YTD - Facility

YTD Avg Total EPOB =
VAR _yearStart = DATE(YEAR(MIN(DateTable[Date])), 1, 1)
VAR _yearEnd = DATE(YEAR(MIN(DateTable[Date])), 12, 31)
RETURN
    CALCULATE(
        AVERAGE(StaffingData[EPOB_TotalFacility]),
        FILTER(ALL(DateTable), DateTable[Date] >= _yearStart && DateTable[Date] <= _yearEnd)
    )
// Format: 0.00  |  Display Folder: YTD - Facility

YTD Avg Variable FTE =
VAR _yearStart = DATE(YEAR(MIN(DateTable[Date])), 1, 1)
VAR _yearEnd = DATE(YEAR(MIN(DateTable[Date])), 12, 31)
RETURN
    CALCULATE(
        AVERAGE(StaffingData[VarAdjFTE]),
        FILTER(ALL(DateTable), DateTable[Date] >= _yearStart && DateTable[Date] <= _yearEnd)
    )
// Format: 0.0  |  Display Folder: YTD - Facility

YTD Avg Fixed FTE =
VAR _yearStart = DATE(YEAR(MIN(DateTable[Date])), 1, 1)
VAR _yearEnd = DATE(YEAR(MIN(DateTable[Date])), 12, 31)
RETURN
    CALCULATE(
        AVERAGE(StaffingData[FixedFTE]),
        FILTER(ALL(DateTable), DateTable[Date] >= _yearStart && DateTable[Date] <= _yearEnd)
    )
// Format: 0.0  |  Display Folder: YTD - Facility

YTD Avg Grand FTE =
VAR _yearStart = DATE(YEAR(MIN(DateTable[Date])), 1, 1)
VAR _yearEnd = DATE(YEAR(MIN(DateTable[Date])), 12, 31)
RETURN
    CALCULATE(
        AVERAGE(StaffingData[GrandAdjFTE]),
        FILTER(ALL(DateTable), DateTable[Date] >= _yearStart && DateTable[Date] <= _yearEnd)
    )
// Format: 0.0  |  Display Folder: YTD - Facility

YTD Avg Total Staff =
VAR _yearStart = DATE(YEAR(MIN(DateTable[Date])), 1, 1)
VAR _yearEnd = DATE(YEAR(MIN(DateTable[Date])), 12, 31)
RETURN
    CALCULATE(
        AVERAGE(StaffingData[Total_ShiftStaff]),
        FILTER(ALL(DateTable), DateTable[Date] >= _yearStart && DateTable[Date] <= _yearEnd)
    )
// Format: 0.0  |  Display Folder: YTD - Facility

YTD Total OT Hours =
VAR _yearStart = DATE(YEAR(MIN(DateTable[Date])), 1, 1)
VAR _yearEnd = DATE(YEAR(MIN(DateTable[Date])), 12, 31)
RETURN
    CALCULATE(
        SUM(StaffingData[Actual_OT_Total]),
        FILTER(ALL(DateTable), DateTable[Date] >= _yearStart && DateTable[Date] <= _yearEnd)
    )
// Format: 0.0  |  Display Folder: YTD - Facility

YTD Avg Hours Variance =
VAR _yearStart = DATE(YEAR(MIN(DateTable[Date])), 1, 1)
VAR _yearEnd = DATE(YEAR(MIN(DateTable[Date])), 12, 31)
RETURN
    CALCULATE(
        AVERAGE(StaffingData[Variance_VarHrsDay_Total]),
        FILTER(ALL(DateTable), DateTable[Date] >= _yearStart && DateTable[Date] <= _yearEnd)
    )
// Format: +0.0;-0.0;0.0  |  Display Folder: YTD - Facility

YTD Days Count =
VAR _yearStart = DATE(YEAR(MIN(DateTable[Date])), 1, 1)
VAR _yearEnd = DATE(YEAR(MIN(DateTable[Date])), 12, 31)
RETURN
    CALCULATE(
        COUNTROWS(StaffingData),
        FILTER(ALL(DateTable), DateTable[Date] >= _yearStart && DateTable[Date] <= _yearEnd)
    )
// Format: #,0  |  Display Folder: YTD - Facility


// ── YTD: By Unit (Avg Daily Census) ──────────────────────────────────────

YTD Avg Census 1East =
VAR _yearStart = DATE(YEAR(MIN(DateTable[Date])), 1, 1)
VAR _yearEnd = DATE(YEAR(MIN(DateTable[Date])), 12, 31)
RETURN
    CALCULATE(AVERAGE(StaffingData[Census_1East]), FILTER(ALL(DateTable), DateTable[Date] >= _yearStart && DateTable[Date] <= _yearEnd))
// Format: 0.0  |  Display Folder: YTD - By Unit

YTD Avg Census 2East =
VAR _yearStart = DATE(YEAR(MIN(DateTable[Date])), 1, 1)
VAR _yearEnd = DATE(YEAR(MIN(DateTable[Date])), 12, 31)
RETURN
    CALCULATE(AVERAGE(StaffingData[Census_2East]), FILTER(ALL(DateTable), DateTable[Date] >= _yearStart && DateTable[Date] <= _yearEnd))
// Format: 0.0  |  Display Folder: YTD - By Unit

YTD Avg Census 2West =
VAR _yearStart = DATE(YEAR(MIN(DateTable[Date])), 1, 1)
VAR _yearEnd = DATE(YEAR(MIN(DateTable[Date])), 12, 31)
RETURN
    CALCULATE(AVERAGE(StaffingData[Census_2West]), FILTER(ALL(DateTable), DateTable[Date] >= _yearStart && DateTable[Date] <= _yearEnd))
// Format: 0.0  |  Display Folder: YTD - By Unit

YTD Avg Census 3East =
VAR _yearStart = DATE(YEAR(MIN(DateTable[Date])), 1, 1)
VAR _yearEnd = DATE(YEAR(MIN(DateTable[Date])), 12, 31)
RETURN
    CALCULATE(AVERAGE(StaffingData[Census_3East]), FILTER(ALL(DateTable), DateTable[Date] >= _yearStart && DateTable[Date] <= _yearEnd))
// Format: 0.0  |  Display Folder: YTD - By Unit

YTD Avg Census 3West =
VAR _yearStart = DATE(YEAR(MIN(DateTable[Date])), 1, 1)
VAR _yearEnd = DATE(YEAR(MIN(DateTable[Date])), 12, 31)
RETURN
    CALCULATE(AVERAGE(StaffingData[Census_3West]), FILTER(ALL(DateTable), DateTable[Date] >= _yearStart && DateTable[Date] <= _yearEnd))
// Format: 0.0  |  Display Folder: YTD - By Unit

YTD Avg Census HRC =
VAR _yearStart = DATE(YEAR(MIN(DateTable[Date])), 1, 1)
VAR _yearEnd = DATE(YEAR(MIN(DateTable[Date])), 12, 31)
RETURN
    CALCULATE(AVERAGE(StaffingData[Census_HRC]), FILTER(ALL(DateTable), DateTable[Date] >= _yearStart && DateTable[Date] <= _yearEnd))
// Format: 0.0  |  Display Folder: YTD - By Unit


// ── YTD: By Unit (Occupancy %) ───────────────────────────────────────────

YTD Avg Occ% 1East = DIVIDE([YTD Avg Census 1East], 18, 0) * 100
// Format: 0.0  |  Display Folder: YTD - By Unit

YTD Avg Occ% 2East = DIVIDE([YTD Avg Census 2East], 20, 0) * 100
// Format: 0.0  |  Display Folder: YTD - By Unit

YTD Avg Occ% 2West = DIVIDE([YTD Avg Census 2West], 20, 0) * 100
// Format: 0.0  |  Display Folder: YTD - By Unit

YTD Avg Occ% 3East = DIVIDE([YTD Avg Census 3East], 20, 0) * 100
// Format: 0.0  |  Display Folder: YTD - By Unit

YTD Avg Occ% 3West = DIVIDE([YTD Avg Census 3West], 20, 0) * 100
// Format: 0.0  |  Display Folder: YTD - By Unit

YTD Avg Occ% HRC = DIVIDE([YTD Avg Census HRC], 16, 0) * 100
// Format: 0.0  |  Display Folder: YTD - By Unit


// ── YTD: By Unit (Total OT Hours) ───────────────────────────────────────

YTD OT 1East =
VAR _yearStart = DATE(YEAR(MIN(DateTable[Date])), 1, 1)
VAR _yearEnd = DATE(YEAR(MIN(DateTable[Date])), 12, 31)
RETURN
    CALCULATE(SUM(StaffingData[Actual_OT_1East]), FILTER(ALL(DateTable), DateTable[Date] >= _yearStart && DateTable[Date] <= _yearEnd))
// Format: 0.0  |  Display Folder: YTD - By Unit

YTD OT 2East =
VAR _yearStart = DATE(YEAR(MIN(DateTable[Date])), 1, 1)
VAR _yearEnd = DATE(YEAR(MIN(DateTable[Date])), 12, 31)
RETURN
    CALCULATE(SUM(StaffingData[Actual_OT_2East]), FILTER(ALL(DateTable), DateTable[Date] >= _yearStart && DateTable[Date] <= _yearEnd))
// Format: 0.0  |  Display Folder: YTD - By Unit

YTD OT 2West =
VAR _yearStart = DATE(YEAR(MIN(DateTable[Date])), 1, 1)
VAR _yearEnd = DATE(YEAR(MIN(DateTable[Date])), 12, 31)
RETURN
    CALCULATE(SUM(StaffingData[Actual_OT_2West]), FILTER(ALL(DateTable), DateTable[Date] >= _yearStart && DateTable[Date] <= _yearEnd))
// Format: 0.0  |  Display Folder: YTD - By Unit

YTD OT 3East =
VAR _yearStart = DATE(YEAR(MIN(DateTable[Date])), 1, 1)
VAR _yearEnd = DATE(YEAR(MIN(DateTable[Date])), 12, 31)
RETURN
    CALCULATE(SUM(StaffingData[Actual_OT_3East]), FILTER(ALL(DateTable), DateTable[Date] >= _yearStart && DateTable[Date] <= _yearEnd))
// Format: 0.0  |  Display Folder: YTD - By Unit

YTD OT 3West =
VAR _yearStart = DATE(YEAR(MIN(DateTable[Date])), 1, 1)
VAR _yearEnd = DATE(YEAR(MIN(DateTable[Date])), 12, 31)
RETURN
    CALCULATE(SUM(StaffingData[Actual_OT_3West]), FILTER(ALL(DateTable), DateTable[Date] >= _yearStart && DateTable[Date] <= _yearEnd))
// Format: 0.0  |  Display Folder: YTD - By Unit

YTD OT HRC =
VAR _yearStart = DATE(YEAR(MIN(DateTable[Date])), 1, 1)
VAR _yearEnd = DATE(YEAR(MIN(DateTable[Date])), 12, 31)
RETURN
    CALCULATE(SUM(StaffingData[Actual_OT_HRC]), FILTER(ALL(DateTable), DateTable[Date] >= _yearStart && DateTable[Date] <= _yearEnd))
// Format: 0.0  |  Display Folder: YTD - By Unit
