{
  "compatibilityLevel": 1567,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "en-US",
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"SharePointSiteURL\",\"StaffingData\",\"Units\"]"
      }
    ],
    "expressions": [
      {
        "name": "SharePointSiteURL",
        "kind": "m",
        "expression": [
          "let",
          "    Source = \"https://YOUR_TENANT.sharepoint.com/sites/YOUR_SITE\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
          "in",
          "    Source"
        ],
        "lineageTag": "param-sp-url"
      }
    ],
    "relationships": [
      {
        "name": "DateTable_to_StaffingData",
        "fromTable": "StaffingData",
        "fromColumn": "DateKey",
        "toTable": "DateTable",
        "toColumn": "Date",
        "crossFilteringBehavior": "bothDirections"
      }
    ],
    "tables": [
      {
        "name": "DateTable",
        "lineageTag": "tbl-date",
        "dataCategory": "Time",
        "partitions": [
          {
            "name": "DateTable-Partition",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "CALENDAR(DATE(2025,1,1), DATE(2027,12,31))"
            }
          }
        ],
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "[Date]",
            "isKey": true,
            "lineageTag": "col-date-date",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Year",
            "dataType": "int64",
            "lineageTag": "col-date-year",
            "summarizeBy": "none",
            "type": "calculated",
            "expression": "YEAR([Date])"
          },
          {
            "name": "MonthNum",
            "dataType": "int64",
            "lineageTag": "col-date-monthnum",
            "summarizeBy": "none",
            "type": "calculated",
            "expression": "MONTH([Date])"
          },
          {
            "name": "MonthName",
            "dataType": "string",
            "lineageTag": "col-date-monthname",
            "summarizeBy": "none",
            "type": "calculated",
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNum"
          },
          {
            "name": "Day",
            "dataType": "int64",
            "lineageTag": "col-date-day",
            "summarizeBy": "none",
            "type": "calculated",
            "expression": "DAY([Date])"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "lineageTag": "col-date-quarter",
            "summarizeBy": "none",
            "type": "calculated",
            "expression": "\"Q\" & FORMAT([Date], \"Q\")"
          },
          {
            "name": "YearMonth",
            "dataType": "string",
            "lineageTag": "col-date-yearmonth",
            "summarizeBy": "none",
            "type": "calculated",
            "expression": "FORMAT([Date], \"YYYY-MM\")"
          },
          {
            "name": "DayOfWeek",
            "dataType": "string",
            "lineageTag": "col-date-dow",
            "summarizeBy": "none",
            "type": "calculated",
            "expression": "FORMAT([Date], \"dddd\")"
          },
          {
            "name": "IsCurrentMonth",
            "dataType": "boolean",
            "lineageTag": "col-date-iscurmonth",
            "summarizeBy": "none",
            "type": "calculated",
            "expression": "YEAR([Date]) = YEAR(TODAY()) && MONTH([Date]) = MONTH(TODAY())"
          },
          {
            "name": "IsCurrentYear",
            "dataType": "boolean",
            "lineageTag": "col-date-iscuryear",
            "summarizeBy": "none",
            "type": "calculated",
            "expression": "YEAR([Date]) = YEAR(TODAY())"
          }
        ],
        "measures": [],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "date-table-auto"
          }
        ]
      },
      {
        "name": "Units",
        "lineageTag": "tbl-units",
        "partitions": [
          {
            "name": "Units-Partition",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "DATATABLE(\"UnitKey\", STRING, \"UnitLabel\", STRING, \"UnitType\", STRING, \"MaxBeds\", INTEGER, \"PayrollBU\", STRING, {{\"1East\", \"1 East - Child Acute\", \"acute\", 18, \"Acute Adult-100E\"}, {\"2East\", \"2 East - Adult Acute\", \"acute\", 20, \"Acute Child-200E\"}, {\"2West\", \"2 West - Adolescent\", \"acute\", 20, \"Acute Adol-200W\"}, {\"3East\", \"3 East - Adult Acute\", \"acute\", 20, \"Acute Adult-300E\"}, {\"3West\", \"3 West - Adult Acute\", \"acute\", 20, \"Acute Adult-300W\"}, {\"HRC\", \"HRC - SUD/Detox ASAM 3.7\", \"detox\", 16, \"Acute Adult-100\"}})"
            }
          }
        ],
        "columns": [
          {
            "name": "UnitKey",
            "dataType": "string",
            "sourceColumn": "UnitKey",
            "lineageTag": "col-unit-key",
            "summarizeBy": "none"
          },
          {
            "name": "UnitLabel",
            "dataType": "string",
            "sourceColumn": "UnitLabel",
            "lineageTag": "col-unit-label",
            "summarizeBy": "none"
          },
          {
            "name": "UnitType",
            "dataType": "string",
            "sourceColumn": "UnitType",
            "lineageTag": "col-unit-type",
            "summarizeBy": "none"
          },
          {
            "name": "MaxBeds",
            "dataType": "int64",
            "sourceColumn": "MaxBeds",
            "lineageTag": "col-unit-maxbeds",
            "summarizeBy": "sum"
          },
          {
            "name": "PayrollBU",
            "dataType": "string",
            "sourceColumn": "PayrollBU",
            "lineageTag": "col-unit-payrollbu",
            "summarizeBy": "none"
          }
        ]
      },
      {
        "name": "StaffingData",
        "lineageTag": "tbl-staffing",
        "partitions": [
          {
            "name": "StaffingData-Partition",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = SharePoint.Tables(SharePointSiteURL, [Implementation=\"2.0\", ApiVersion=15]),",
                "    StaffingMatrix = Source{[Title=\"StaffingMatrix\"]}[Items],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(StaffingMatrix, {\"Timestamp\", \"Date\", \"TimeEntryDate\", \"TotalStaffedBeds\", \"TotalCensus\", \"OccupancyPct\", \"Census_1East\", \"OccPct_1East\", \"Census_2East\", \"OccPct_2East\", \"Census_2West\", \"OccPct_2West\", \"Census_3East\", \"OccPct_3East\", \"Census_3West\", \"OccPct_3West\", \"Census_HRC\", \"OccPct_HRC\", \"ObsHrs_Total\", \"ObsHrs_1East\", \"ObsHrs_2East\", \"ObsHrs_2West\", \"ObsHrs_3East\", \"ObsHrs_3West\", \"ObsHrs_HRC\", \"NP_ModelPct\", \"NP_Multiplier\", \"NP_1East\", \"NP_2East\", \"NP_2West\", \"NP_3East\", \"NP_3West\", \"NP_HRC\", \"1East_Day_RN\", \"1East_Day_LPN\", \"1East_Day_Tech\", \"1East_Evening_RN\", \"1East_Evening_LPN\", \"1East_Evening_Tech\", \"1East_Night_RN\", \"1East_Night_LPN\", \"1East_Night_Tech\", \"1East_ShiftTotal\", \"1East_Ratio_Day\", \"1East_Ratio_Eve\", \"1East_Ratio_Night\", \"2East_Day_RN\", \"2East_Day_LPN\", \"2East_Day_Tech\", \"2East_Evening_RN\", \"2East_Evening_LPN\", \"2East_Evening_Tech\", \"2East_Night_RN\", \"2East_Night_LPN\", \"2East_Night_Tech\", \"2East_ShiftTotal\", \"2East_Ratio_Day\", \"2East_Ratio_Eve\", \"2East_Ratio_Night\", \"2West_Day_RN\", \"2West_Day_LPN\", \"2West_Day_Tech\", \"2West_Evening_RN\", \"2West_Evening_LPN\", \"2West_Evening_Tech\", \"2West_Night_RN\", \"2West_Night_LPN\", \"2West_Night_Tech\", \"2West_ShiftTotal\", \"2West_Ratio_Day\", \"2West_Ratio_Eve\", \"2West_Ratio_Night\", \"3East_Day_RN\", \"3East_Day_LPN\", \"3East_Day_Tech\", \"3East_Evening_RN\", \"3East_Evening_LPN\", \"3East_Evening_Tech\", \"3East_Night_RN\", \"3East_Night_LPN\", \"3East_Night_Tech\", \"3East_ShiftTotal\", \"3East_Ratio_Day\", \"3East_Ratio_Eve\", \"3East_Ratio_Night\", \"3West_Day_RN\", \"3West_Day_LPN\", \"3West_Day_Tech\", \"3West_Evening_RN\", \"3West_Evening_LPN\", \"3West_Evening_Tech\", \"3West_Night_RN\", \"3West_Night_LPN\", \"3West_Night_Tech\", \"3West_ShiftTotal\", \"3West_Ratio_Day\", \"3West_Ratio_Eve\", \"3West_Ratio_Night\", \"HRC_Day_RN\", \"HRC_Day_LPN\", \"HRC_Day_Tech\", \"HRC_Evening_RN\", \"HRC_Evening_LPN\", \"HRC_Evening_Tech\", \"HRC_Night_RN\", \"HRC_Night_LPN\", \"HRC_Night_Tech\", \"HRC_ShiftTotal\", \"HRC_Ratio_Day\", \"HRC_Ratio_Eve\", \"HRC_Ratio_Night\", \"Total_RN\", \"Total_LPN\", \"Total_Tech\", \"Total_ShiftStaff\", \"StaffPerShift\", \"FloatShiftPositions\", \"RN_ProdFTE\", \"RN_AdjFTE\", \"LPN_ProdFTE\", \"LPN_AdjFTE\", \"Tech_ProdFTE\", \"Tech_AdjFTE\", \"Float_ProdFTE\", \"Float_AdjFTE\", \"OneOne_ProdFTE\", \"OneOne_AdjFTE\", \"VarProdFTE\", \"VarAdjFTE\", \"VarNP_Add\", \"FixedFTE\", \"FixedHC\", \"FixedSource\", \"GrandProdFTE\", \"GrandAdjFTE\", \"EPOB_DirectCare\", \"EPOB_TotalFacility\", \"EPOB_Productive\", \"EPOB_VarPerPatient\", \"EPOB_FixPerPatient\", \"HasPayrollData\", \"PayrollFileName\", \"PayrollDayCount\", \"PayrollStartDate\", \"PayrollEndDate\", \"Actual_HrsDay_1East\", \"Actual_HC_1East\", \"Actual_OT_1East\", \"Actual_NpHrs_1East\", \"Actual_Wages_1East\", \"Model_HrsDay_1East\", \"Variance_HrsDay_1East\", \"Variance_Pct_1East\", \"Actual_HrsDay_2East\", \"Actual_HC_2East\", \"Actual_OT_2East\", \"Actual_NpHrs_2East\", \"Actual_Wages_2East\", \"Model_HrsDay_2East\", \"Variance_HrsDay_2East\", \"Variance_Pct_2East\", \"Actual_HrsDay_2West\", \"Actual_HC_2West\", \"Actual_OT_2West\", \"Actual_NpHrs_2West\", \"Actual_Wages_2West\", \"Model_HrsDay_2West\", \"Variance_HrsDay_2West\", \"Variance_Pct_2West\", \"Actual_HrsDay_3East\", \"Actual_HC_3East\", \"Actual_OT_3East\", \"Actual_NpHrs_3East\", \"Actual_Wages_3East\", \"Model_HrsDay_3East\", \"Variance_HrsDay_3East\", \"Variance_Pct_3East\", \"Actual_HrsDay_3West\", \"Actual_HC_3West\", \"Actual_OT_3West\", \"Actual_NpHrs_3West\", \"Actual_Wages_3West\", \"Model_HrsDay_3West\", \"Variance_HrsDay_3West\", \"Variance_Pct_3West\", \"Actual_HrsDay_HRC\", \"Actual_HC_HRC\", \"Actual_OT_HRC\", \"Actual_NpHrs_HRC\", \"Actual_Wages_HRC\", \"Model_HrsDay_HRC\", \"Variance_HrsDay_HRC\", \"Variance_Pct_HRC\", \"Actual_VarHrsDay_Total\", \"Actual_FixHrsDay_Total\", \"Actual_VarHC_Total\", \"Actual_FixHC_Total\", \"Actual_OT_Total\", \"Model_VarHrsDay_Total\", \"Variance_VarHrsDay_Total\", \"Variance_VarPct_Total\", \"Actual_VarFTE\", \"Actual_FixFTE\", \"Actual_TotalFTE\", \"Actual_EPOB_DC\", \"Actual_EPOB_Total\", \"EPOB_DC_Variance\", \"EPOB_Total_Variance\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Other Columns\", {{\"Timestamp\", type text}, {\"Date\", type text}, {\"TimeEntryDate\", type text}, {\"TotalStaffedBeds\", type number}, {\"TotalCensus\", type number}, {\"OccupancyPct\", type number}, {\"Census_1East\", type number}, {\"OccPct_1East\", type number}, {\"Census_2East\", type number}, {\"OccPct_2East\", type number}, {\"Census_2West\", type number}, {\"OccPct_2West\", type number}, {\"Census_3East\", type number}, {\"OccPct_3East\", type number}, {\"Census_3West\", type number}, {\"OccPct_3West\", type number}, {\"Census_HRC\", type number}, {\"OccPct_HRC\", type number}, {\"ObsHrs_Total\", type number}, {\"ObsHrs_1East\", type number}, {\"ObsHrs_2East\", type number}, {\"ObsHrs_2West\", type number}, {\"ObsHrs_3East\", type number}, {\"ObsHrs_3West\", type number}, {\"ObsHrs_HRC\", type number}, {\"NP_ModelPct\", type number}, {\"NP_Multiplier\", type number}, {\"NP_1East\", type number}, {\"NP_2East\", type number}, {\"NP_2West\", type number}, {\"NP_3East\", type number}, {\"NP_3West\", type number}, {\"NP_HRC\", type number}, {\"1East_Day_RN\", type number}, {\"1East_Day_LPN\", type number}, {\"1East_Day_Tech\", type number}, {\"1East_Evening_RN\", type number}, {\"1East_Evening_LPN\", type number}, {\"1East_Evening_Tech\", type number}, {\"1East_Night_RN\", type number}, {\"1East_Night_LPN\", type number}, {\"1East_Night_Tech\", type number}, {\"1East_ShiftTotal\", type number}, {\"1East_Ratio_Day\", type number}, {\"1East_Ratio_Eve\", type number}, {\"1East_Ratio_Night\", type number}, {\"2East_Day_RN\", type number}, {\"2East_Day_LPN\", type number}, {\"2East_Day_Tech\", type number}, {\"2East_Evening_RN\", type number}, {\"2East_Evening_LPN\", type number}, {\"2East_Evening_Tech\", type number}, {\"2East_Night_RN\", type number}, {\"2East_Night_LPN\", type number}, {\"2East_Night_Tech\", type number}, {\"2East_ShiftTotal\", type number}, {\"2East_Ratio_Day\", type number}, {\"2East_Ratio_Eve\", type number}, {\"2East_Ratio_Night\", type number}, {\"2West_Day_RN\", type number}, {\"2West_Day_LPN\", type number}, {\"2West_Day_Tech\", type number}, {\"2West_Evening_RN\", type number}, {\"2West_Evening_LPN\", type number}, {\"2West_Evening_Tech\", type number}, {\"2West_Night_RN\", type number}, {\"2West_Night_LPN\", type number}, {\"2West_Night_Tech\", type number}, {\"2West_ShiftTotal\", type number}, {\"2West_Ratio_Day\", type number}, {\"2West_Ratio_Eve\", type number}, {\"2West_Ratio_Night\", type number}, {\"3East_Day_RN\", type number}, {\"3East_Day_LPN\", type number}, {\"3East_Day_Tech\", type number}, {\"3East_Evening_RN\", type number}, {\"3East_Evening_LPN\", type number}, {\"3East_Evening_Tech\", type number}, {\"3East_Night_RN\", type number}, {\"3East_Night_LPN\", type number}, {\"3East_Night_Tech\", type number}, {\"3East_ShiftTotal\", type number}, {\"3East_Ratio_Day\", type number}, {\"3East_Ratio_Eve\", type number}, {\"3East_Ratio_Night\", type number}, {\"3West_Day_RN\", type number}, {\"3West_Day_LPN\", type number}, {\"3West_Day_Tech\", type number}, {\"3West_Evening_RN\", type number}, {\"3West_Evening_LPN\", type number}, {\"3West_Evening_Tech\", type number}, {\"3West_Night_RN\", type number}, {\"3West_Night_LPN\", type number}, {\"3West_Night_Tech\", type number}, {\"3West_ShiftTotal\", type number}, {\"3West_Ratio_Day\", type number}, {\"3West_Ratio_Eve\", type number}, {\"3West_Ratio_Night\", type number}, {\"HRC_Day_RN\", type number}, {\"HRC_Day_LPN\", type number}, {\"HRC_Day_Tech\", type number}, {\"HRC_Evening_RN\", type number}, {\"HRC_Evening_LPN\", type number}, {\"HRC_Evening_Tech\", type number}, {\"HRC_Night_RN\", type number}, {\"HRC_Night_LPN\", type number}, {\"HRC_Night_Tech\", type number}, {\"HRC_ShiftTotal\", type number}, {\"HRC_Ratio_Day\", type number}, {\"HRC_Ratio_Eve\", type number}, {\"HRC_Ratio_Night\", type number}, {\"Total_RN\", type number}, {\"Total_LPN\", type number}, {\"Total_Tech\", type number}, {\"Total_ShiftStaff\", type number}, {\"StaffPerShift\", type number}, {\"FloatShiftPositions\", type number}, {\"RN_ProdFTE\", type number}, {\"RN_AdjFTE\", type number}, {\"LPN_ProdFTE\", type number}, {\"LPN_AdjFTE\", type number}, {\"Tech_ProdFTE\", type number}, {\"Tech_AdjFTE\", type number}, {\"Float_ProdFTE\", type number}, {\"Float_AdjFTE\", type number}, {\"OneOne_ProdFTE\", type number}, {\"OneOne_AdjFTE\", type number}, {\"VarProdFTE\", type number}, {\"VarAdjFTE\", type number}, {\"VarNP_Add\", type number}, {\"FixedFTE\", type number}, {\"FixedHC\", type number}, {\"FixedSource\", type text}, {\"GrandProdFTE\", type number}, {\"GrandAdjFTE\", type number}, {\"EPOB_DirectCare\", type number}, {\"EPOB_TotalFacility\", type number}, {\"EPOB_Productive\", type number}, {\"EPOB_VarPerPatient\", type number}, {\"EPOB_FixPerPatient\", type number}, {\"HasPayrollData\", type logical}, {\"PayrollFileName\", type text}, {\"PayrollDayCount\", type number}, {\"PayrollStartDate\", type text}, {\"PayrollEndDate\", type text}, {\"Actual_HrsDay_1East\", type number}, {\"Actual_HC_1East\", type number}, {\"Actual_OT_1East\", type number}, {\"Actual_NpHrs_1East\", type number}, {\"Actual_Wages_1East\", type number}, {\"Model_HrsDay_1East\", type number}, {\"Variance_HrsDay_1East\", type number}, {\"Variance_Pct_1East\", type number}, {\"Actual_HrsDay_2East\", type number}, {\"Actual_HC_2East\", type number}, {\"Actual_OT_2East\", type number}, {\"Actual_NpHrs_2East\", type number}, {\"Actual_Wages_2East\", type number}, {\"Model_HrsDay_2East\", type number}, {\"Variance_HrsDay_2East\", type number}, {\"Variance_Pct_2East\", type number}, {\"Actual_HrsDay_2West\", type number}, {\"Actual_HC_2West\", type number}, {\"Actual_OT_2West\", type number}, {\"Actual_NpHrs_2West\", type number}, {\"Actual_Wages_2West\", type number}, {\"Model_HrsDay_2West\", type number}, {\"Variance_HrsDay_2West\", type number}, {\"Variance_Pct_2West\", type number}, {\"Actual_HrsDay_3East\", type number}, {\"Actual_HC_3East\", type number}, {\"Actual_OT_3East\", type number}, {\"Actual_NpHrs_3East\", type number}, {\"Actual_Wages_3East\", type number}, {\"Model_HrsDay_3East\", type number}, {\"Variance_HrsDay_3East\", type number}, {\"Variance_Pct_3East\", type number}, {\"Actual_HrsDay_3West\", type number}, {\"Actual_HC_3West\", type number}, {\"Actual_OT_3West\", type number}, {\"Actual_NpHrs_3West\", type number}, {\"Actual_Wages_3West\", type number}, {\"Model_HrsDay_3West\", type number}, {\"Variance_HrsDay_3West\", type number}, {\"Variance_Pct_3West\", type number}, {\"Actual_HrsDay_HRC\", type number}, {\"Actual_HC_HRC\", type number}, {\"Actual_OT_HRC\", type number}, {\"Actual_NpHrs_HRC\", type number}, {\"Actual_Wages_HRC\", type number}, {\"Model_HrsDay_HRC\", type number}, {\"Variance_HrsDay_HRC\", type number}, {\"Variance_Pct_HRC\", type number}, {\"Actual_VarHrsDay_Total\", type number}, {\"Actual_FixHrsDay_Total\", type number}, {\"Actual_VarHC_Total\", type number}, {\"Actual_FixHC_Total\", type number}, {\"Actual_OT_Total\", type number}, {\"Model_VarHrsDay_Total\", type number}, {\"Variance_VarHrsDay_Total\", type number}, {\"Variance_VarPct_Total\", type number}, {\"Actual_VarFTE\", type number}, {\"Actual_FixFTE\", type number}, {\"Actual_TotalFTE\", type number}, {\"Actual_EPOB_DC\", type number}, {\"Actual_EPOB_Total\", type number}, {\"EPOB_DC_Variance\", type number}, {\"EPOB_Total_Variance\", type number}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "columns": [
          {
            "name": "Timestamp",
            "dataType": "string",
            "sourceColumn": "Timestamp",
            "lineageTag": "col-sd-0",
            "summarizeBy": "none"
          },
          {
            "name": "Date",
            "dataType": "string",
            "sourceColumn": "Date",
            "lineageTag": "col-sd-1",
            "summarizeBy": "none"
          },
          {
            "name": "TimeEntryDate",
            "dataType": "string",
            "sourceColumn": "TimeEntryDate",
            "lineageTag": "col-sd-2",
            "summarizeBy": "none"
          },
          {
            "name": "TotalStaffedBeds",
            "dataType": "double",
            "sourceColumn": "TotalStaffedBeds",
            "lineageTag": "col-sd-3",
            "summarizeBy": "sum"
          },
          {
            "name": "TotalCensus",
            "dataType": "double",
            "sourceColumn": "TotalCensus",
            "lineageTag": "col-sd-4",
            "summarizeBy": "sum"
          },
          {
            "name": "OccupancyPct",
            "dataType": "double",
            "sourceColumn": "OccupancyPct",
            "lineageTag": "col-sd-5",
            "summarizeBy": "none"
          },
          {
            "name": "Census_1East",
            "dataType": "double",
            "sourceColumn": "Census_1East",
            "lineageTag": "col-sd-6",
            "summarizeBy": "none"
          },
          {
            "name": "OccPct_1East",
            "dataType": "double",
            "sourceColumn": "OccPct_1East",
            "lineageTag": "col-sd-7",
            "summarizeBy": "none"
          },
          {
            "name": "Census_2East",
            "dataType": "double",
            "sourceColumn": "Census_2East",
            "lineageTag": "col-sd-8",
            "summarizeBy": "none"
          },
          {
            "name": "OccPct_2East",
            "dataType": "double",
            "sourceColumn": "OccPct_2East",
            "lineageTag": "col-sd-9",
            "summarizeBy": "none"
          },
          {
            "name": "Census_2West",
            "dataType": "double",
            "sourceColumn": "Census_2West",
            "lineageTag": "col-sd-10",
            "summarizeBy": "none"
          },
          {
            "name": "OccPct_2West",
            "dataType": "double",
            "sourceColumn": "OccPct_2West",
            "lineageTag": "col-sd-11",
            "summarizeBy": "none"
          },
          {
            "name": "Census_3East",
            "dataType": "double",
            "sourceColumn": "Census_3East",
            "lineageTag": "col-sd-12",
            "summarizeBy": "none"
          },
          {
            "name": "OccPct_3East",
            "dataType": "double",
            "sourceColumn": "OccPct_3East",
            "lineageTag": "col-sd-13",
            "summarizeBy": "none"
          },
          {
            "name": "Census_3West",
            "dataType": "double",
            "sourceColumn": "Census_3West",
            "lineageTag": "col-sd-14",
            "summarizeBy": "none"
          },
          {
            "name": "OccPct_3West",
            "dataType": "double",
            "sourceColumn": "OccPct_3West",
            "lineageTag": "col-sd-15",
            "summarizeBy": "none"
          },
          {
            "name": "Census_HRC",
            "dataType": "double",
            "sourceColumn": "Census_HRC",
            "lineageTag": "col-sd-16",
            "summarizeBy": "none"
          },
          {
            "name": "OccPct_HRC",
            "dataType": "double",
            "sourceColumn": "OccPct_HRC",
            "lineageTag": "col-sd-17",
            "summarizeBy": "none"
          },
          {
            "name": "ObsHrs_Total",
            "dataType": "double",
            "sourceColumn": "ObsHrs_Total",
            "lineageTag": "col-sd-18",
            "summarizeBy": "sum"
          },
          {
            "name": "ObsHrs_1East",
            "dataType": "double",
            "sourceColumn": "ObsHrs_1East",
            "lineageTag": "col-sd-19",
            "summarizeBy": "sum"
          },
          {
            "name": "ObsHrs_2East",
            "dataType": "double",
            "sourceColumn": "ObsHrs_2East",
            "lineageTag": "col-sd-20",
            "summarizeBy": "sum"
          },
          {
            "name": "ObsHrs_2West",
            "dataType": "double",
            "sourceColumn": "ObsHrs_2West",
            "lineageTag": "col-sd-21",
            "summarizeBy": "sum"
          },
          {
            "name": "ObsHrs_3East",
            "dataType": "double",
            "sourceColumn": "ObsHrs_3East",
            "lineageTag": "col-sd-22",
            "summarizeBy": "sum"
          },
          {
            "name": "ObsHrs_3West",
            "dataType": "double",
            "sourceColumn": "ObsHrs_3West",
            "lineageTag": "col-sd-23",
            "summarizeBy": "sum"
          },
          {
            "name": "ObsHrs_HRC",
            "dataType": "double",
            "sourceColumn": "ObsHrs_HRC",
            "lineageTag": "col-sd-24",
            "summarizeBy": "sum"
          },
          {
            "name": "NP_ModelPct",
            "dataType": "double",
            "sourceColumn": "NP_ModelPct",
            "lineageTag": "col-sd-25",
            "summarizeBy": "none"
          },
          {
            "name": "NP_Multiplier",
            "dataType": "double",
            "sourceColumn": "NP_Multiplier",
            "lineageTag": "col-sd-26",
            "summarizeBy": "none"
          },
          {
            "name": "NP_1East",
            "dataType": "double",
            "sourceColumn": "NP_1East",
            "lineageTag": "col-sd-27",
            "summarizeBy": "none"
          },
          {
            "name": "NP_2East",
            "dataType": "double",
            "sourceColumn": "NP_2East",
            "lineageTag": "col-sd-28",
            "summarizeBy": "none"
          },
          {
            "name": "NP_2West",
            "dataType": "double",
            "sourceColumn": "NP_2West",
            "lineageTag": "col-sd-29",
            "summarizeBy": "none"
          },
          {
            "name": "NP_3East",
            "dataType": "double",
            "sourceColumn": "NP_3East",
            "lineageTag": "col-sd-30",
            "summarizeBy": "none"
          },
          {
            "name": "NP_3West",
            "dataType": "double",
            "sourceColumn": "NP_3West",
            "lineageTag": "col-sd-31",
            "summarizeBy": "none"
          },
          {
            "name": "NP_HRC",
            "dataType": "double",
            "sourceColumn": "NP_HRC",
            "lineageTag": "col-sd-32",
            "summarizeBy": "none"
          },
          {
            "name": "1East_Day_RN",
            "dataType": "double",
            "sourceColumn": "1East_Day_RN",
            "lineageTag": "col-sd-33",
            "summarizeBy": "sum"
          },
          {
            "name": "1East_Day_LPN",
            "dataType": "double",
            "sourceColumn": "1East_Day_LPN",
            "lineageTag": "col-sd-34",
            "summarizeBy": "sum"
          },
          {
            "name": "1East_Day_Tech",
            "dataType": "double",
            "sourceColumn": "1East_Day_Tech",
            "lineageTag": "col-sd-35",
            "summarizeBy": "sum"
          },
          {
            "name": "1East_Evening_RN",
            "dataType": "double",
            "sourceColumn": "1East_Evening_RN",
            "lineageTag": "col-sd-36",
            "summarizeBy": "sum"
          },
          {
            "name": "1East_Evening_LPN",
            "dataType": "double",
            "sourceColumn": "1East_Evening_LPN",
            "lineageTag": "col-sd-37",
            "summarizeBy": "sum"
          },
          {
            "name": "1East_Evening_Tech",
            "dataType": "double",
            "sourceColumn": "1East_Evening_Tech",
            "lineageTag": "col-sd-38",
            "summarizeBy": "sum"
          },
          {
            "name": "1East_Night_RN",
            "dataType": "double",
            "sourceColumn": "1East_Night_RN",
            "lineageTag": "col-sd-39",
            "summarizeBy": "sum"
          },
          {
            "name": "1East_Night_LPN",
            "dataType": "double",
            "sourceColumn": "1East_Night_LPN",
            "lineageTag": "col-sd-40",
            "summarizeBy": "sum"
          },
          {
            "name": "1East_Night_Tech",
            "dataType": "double",
            "sourceColumn": "1East_Night_Tech",
            "lineageTag": "col-sd-41",
            "summarizeBy": "sum"
          },
          {
            "name": "1East_ShiftTotal",
            "dataType": "double",
            "sourceColumn": "1East_ShiftTotal",
            "lineageTag": "col-sd-42",
            "summarizeBy": "sum"
          },
          {
            "name": "1East_Ratio_Day",
            "dataType": "double",
            "sourceColumn": "1East_Ratio_Day",
            "lineageTag": "col-sd-43",
            "summarizeBy": "sum"
          },
          {
            "name": "1East_Ratio_Eve",
            "dataType": "double",
            "sourceColumn": "1East_Ratio_Eve",
            "lineageTag": "col-sd-44",
            "summarizeBy": "sum"
          },
          {
            "name": "1East_Ratio_Night",
            "dataType": "double",
            "sourceColumn": "1East_Ratio_Night",
            "lineageTag": "col-sd-45",
            "summarizeBy": "sum"
          },
          {
            "name": "2East_Day_RN",
            "dataType": "double",
            "sourceColumn": "2East_Day_RN",
            "lineageTag": "col-sd-46",
            "summarizeBy": "sum"
          },
          {
            "name": "2East_Day_LPN",
            "dataType": "double",
            "sourceColumn": "2East_Day_LPN",
            "lineageTag": "col-sd-47",
            "summarizeBy": "sum"
          },
          {
            "name": "2East_Day_Tech",
            "dataType": "double",
            "sourceColumn": "2East_Day_Tech",
            "lineageTag": "col-sd-48",
            "summarizeBy": "sum"
          },
          {
            "name": "2East_Evening_RN",
            "dataType": "double",
            "sourceColumn": "2East_Evening_RN",
            "lineageTag": "col-sd-49",
            "summarizeBy": "sum"
          },
          {
            "name": "2East_Evening_LPN",
            "dataType": "double",
            "sourceColumn": "2East_Evening_LPN",
            "lineageTag": "col-sd-50",
            "summarizeBy": "sum"
          },
          {
            "name": "2East_Evening_Tech",
            "dataType": "double",
            "sourceColumn": "2East_Evening_Tech",
            "lineageTag": "col-sd-51",
            "summarizeBy": "sum"
          },
          {
            "name": "2East_Night_RN",
            "dataType": "double",
            "sourceColumn": "2East_Night_RN",
            "lineageTag": "col-sd-52",
            "summarizeBy": "sum"
          },
          {
            "name": "2East_Night_LPN",
            "dataType": "double",
            "sourceColumn": "2East_Night_LPN",
            "lineageTag": "col-sd-53",
            "summarizeBy": "sum"
          },
          {
            "name": "2East_Night_Tech",
            "dataType": "double",
            "sourceColumn": "2East_Night_Tech",
            "lineageTag": "col-sd-54",
            "summarizeBy": "sum"
          },
          {
            "name": "2East_ShiftTotal",
            "dataType": "double",
            "sourceColumn": "2East_ShiftTotal",
            "lineageTag": "col-sd-55",
            "summarizeBy": "sum"
          },
          {
            "name": "2East_Ratio_Day",
            "dataType": "double",
            "sourceColumn": "2East_Ratio_Day",
            "lineageTag": "col-sd-56",
            "summarizeBy": "sum"
          },
          {
            "name": "2East_Ratio_Eve",
            "dataType": "double",
            "sourceColumn": "2East_Ratio_Eve",
            "lineageTag": "col-sd-57",
            "summarizeBy": "sum"
          },
          {
            "name": "2East_Ratio_Night",
            "dataType": "double",
            "sourceColumn": "2East_Ratio_Night",
            "lineageTag": "col-sd-58",
            "summarizeBy": "sum"
          },
          {
            "name": "2West_Day_RN",
            "dataType": "double",
            "sourceColumn": "2West_Day_RN",
            "lineageTag": "col-sd-59",
            "summarizeBy": "sum"
          },
          {
            "name": "2West_Day_LPN",
            "dataType": "double",
            "sourceColumn": "2West_Day_LPN",
            "lineageTag": "col-sd-60",
            "summarizeBy": "sum"
          },
          {
            "name": "2West_Day_Tech",
            "dataType": "double",
            "sourceColumn": "2West_Day_Tech",
            "lineageTag": "col-sd-61",
            "summarizeBy": "sum"
          },
          {
            "name": "2West_Evening_RN",
            "dataType": "double",
            "sourceColumn": "2West_Evening_RN",
            "lineageTag": "col-sd-62",
            "summarizeBy": "sum"
          },
          {
            "name": "2West_Evening_LPN",
            "dataType": "double",
            "sourceColumn": "2West_Evening_LPN",
            "lineageTag": "col-sd-63",
            "summarizeBy": "sum"
          },
          {
            "name": "2West_Evening_Tech",
            "dataType": "double",
            "sourceColumn": "2West_Evening_Tech",
            "lineageTag": "col-sd-64",
            "summarizeBy": "sum"
          },
          {
            "name": "2West_Night_RN",
            "dataType": "double",
            "sourceColumn": "2West_Night_RN",
            "lineageTag": "col-sd-65",
            "summarizeBy": "sum"
          },
          {
            "name": "2West_Night_LPN",
            "dataType": "double",
            "sourceColumn": "2West_Night_LPN",
            "lineageTag": "col-sd-66",
            "summarizeBy": "sum"
          },
          {
            "name": "2West_Night_Tech",
            "dataType": "double",
            "sourceColumn": "2West_Night_Tech",
            "lineageTag": "col-sd-67",
            "summarizeBy": "sum"
          },
          {
            "name": "2West_ShiftTotal",
            "dataType": "double",
            "sourceColumn": "2West_ShiftTotal",
            "lineageTag": "col-sd-68",
            "summarizeBy": "sum"
          },
          {
            "name": "2West_Ratio_Day",
            "dataType": "double",
            "sourceColumn": "2West_Ratio_Day",
            "lineageTag": "col-sd-69",
            "summarizeBy": "sum"
          },
          {
            "name": "2West_Ratio_Eve",
            "dataType": "double",
            "sourceColumn": "2West_Ratio_Eve",
            "lineageTag": "col-sd-70",
            "summarizeBy": "sum"
          },
          {
            "name": "2West_Ratio_Night",
            "dataType": "double",
            "sourceColumn": "2West_Ratio_Night",
            "lineageTag": "col-sd-71",
            "summarizeBy": "sum"
          },
          {
            "name": "3East_Day_RN",
            "dataType": "double",
            "sourceColumn": "3East_Day_RN",
            "lineageTag": "col-sd-72",
            "summarizeBy": "sum"
          },
          {
            "name": "3East_Day_LPN",
            "dataType": "double",
            "sourceColumn": "3East_Day_LPN",
            "lineageTag": "col-sd-73",
            "summarizeBy": "sum"
          },
          {
            "name": "3East_Day_Tech",
            "dataType": "double",
            "sourceColumn": "3East_Day_Tech",
            "lineageTag": "col-sd-74",
            "summarizeBy": "sum"
          },
          {
            "name": "3East_Evening_RN",
            "dataType": "double",
            "sourceColumn": "3East_Evening_RN",
            "lineageTag": "col-sd-75",
            "summarizeBy": "sum"
          },
          {
            "name": "3East_Evening_LPN",
            "dataType": "double",
            "sourceColumn": "3East_Evening_LPN",
            "lineageTag": "col-sd-76",
            "summarizeBy": "sum"
          },
          {
            "name": "3East_Evening_Tech",
            "dataType": "double",
            "sourceColumn": "3East_Evening_Tech",
            "lineageTag": "col-sd-77",
            "summarizeBy": "sum"
          },
          {
            "name": "3East_Night_RN",
            "dataType": "double",
            "sourceColumn": "3East_Night_RN",
            "lineageTag": "col-sd-78",
            "summarizeBy": "sum"
          },
          {
            "name": "3East_Night_LPN",
            "dataType": "double",
            "sourceColumn": "3East_Night_LPN",
            "lineageTag": "col-sd-79",
            "summarizeBy": "sum"
          },
          {
            "name": "3East_Night_Tech",
            "dataType": "double",
            "sourceColumn": "3East_Night_Tech",
            "lineageTag": "col-sd-80",
            "summarizeBy": "sum"
          },
          {
            "name": "3East_ShiftTotal",
            "dataType": "double",
            "sourceColumn": "3East_ShiftTotal",
            "lineageTag": "col-sd-81",
            "summarizeBy": "sum"
          },
          {
            "name": "3East_Ratio_Day",
            "dataType": "double",
            "sourceColumn": "3East_Ratio_Day",
            "lineageTag": "col-sd-82",
            "summarizeBy": "sum"
          },
          {
            "name": "3East_Ratio_Eve",
            "dataType": "double",
            "sourceColumn": "3East_Ratio_Eve",
            "lineageTag": "col-sd-83",
            "summarizeBy": "sum"
          },
          {
            "name": "3East_Ratio_Night",
            "dataType": "double",
            "sourceColumn": "3East_Ratio_Night",
            "lineageTag": "col-sd-84",
            "summarizeBy": "sum"
          },
          {
            "name": "3West_Day_RN",
            "dataType": "double",
            "sourceColumn": "3West_Day_RN",
            "lineageTag": "col-sd-85",
            "summarizeBy": "sum"
          },
          {
            "name": "3West_Day_LPN",
            "dataType": "double",
            "sourceColumn": "3West_Day_LPN",
            "lineageTag": "col-sd-86",
            "summarizeBy": "sum"
          },
          {
            "name": "3West_Day_Tech",
            "dataType": "double",
            "sourceColumn": "3West_Day_Tech",
            "lineageTag": "col-sd-87",
            "summarizeBy": "sum"
          },
          {
            "name": "3West_Evening_RN",
            "dataType": "double",
            "sourceColumn": "3West_Evening_RN",
            "lineageTag": "col-sd-88",
            "summarizeBy": "sum"
          },
          {
            "name": "3West_Evening_LPN",
            "dataType": "double",
            "sourceColumn": "3West_Evening_LPN",
            "lineageTag": "col-sd-89",
            "summarizeBy": "sum"
          },
          {
            "name": "3West_Evening_Tech",
            "dataType": "double",
            "sourceColumn": "3West_Evening_Tech",
            "lineageTag": "col-sd-90",
            "summarizeBy": "sum"
          },
          {
            "name": "3West_Night_RN",
            "dataType": "double",
            "sourceColumn": "3West_Night_RN",
            "lineageTag": "col-sd-91",
            "summarizeBy": "sum"
          },
          {
            "name": "3West_Night_LPN",
            "dataType": "double",
            "sourceColumn": "3West_Night_LPN",
            "lineageTag": "col-sd-92",
            "summarizeBy": "sum"
          },
          {
            "name": "3West_Night_Tech",
            "dataType": "double",
            "sourceColumn": "3West_Night_Tech",
            "lineageTag": "col-sd-93",
            "summarizeBy": "sum"
          },
          {
            "name": "3West_ShiftTotal",
            "dataType": "double",
            "sourceColumn": "3West_ShiftTotal",
            "lineageTag": "col-sd-94",
            "summarizeBy": "sum"
          },
          {
            "name": "3West_Ratio_Day",
            "dataType": "double",
            "sourceColumn": "3West_Ratio_Day",
            "lineageTag": "col-sd-95",
            "summarizeBy": "sum"
          },
          {
            "name": "3West_Ratio_Eve",
            "dataType": "double",
            "sourceColumn": "3West_Ratio_Eve",
            "lineageTag": "col-sd-96",
            "summarizeBy": "sum"
          },
          {
            "name": "3West_Ratio_Night",
            "dataType": "double",
            "sourceColumn": "3West_Ratio_Night",
            "lineageTag": "col-sd-97",
            "summarizeBy": "sum"
          },
          {
            "name": "HRC_Day_RN",
            "dataType": "double",
            "sourceColumn": "HRC_Day_RN",
            "lineageTag": "col-sd-98",
            "summarizeBy": "sum"
          },
          {
            "name": "HRC_Day_LPN",
            "dataType": "double",
            "sourceColumn": "HRC_Day_LPN",
            "lineageTag": "col-sd-99",
            "summarizeBy": "sum"
          },
          {
            "name": "HRC_Day_Tech",
            "dataType": "double",
            "sourceColumn": "HRC_Day_Tech",
            "lineageTag": "col-sd-100",
            "summarizeBy": "sum"
          },
          {
            "name": "HRC_Evening_RN",
            "dataType": "double",
            "sourceColumn": "HRC_Evening_RN",
            "lineageTag": "col-sd-101",
            "summarizeBy": "sum"
          },
          {
            "name": "HRC_Evening_LPN",
            "dataType": "double",
            "sourceColumn": "HRC_Evening_LPN",
            "lineageTag": "col-sd-102",
            "summarizeBy": "sum"
          },
          {
            "name": "HRC_Evening_Tech",
            "dataType": "double",
            "sourceColumn": "HRC_Evening_Tech",
            "lineageTag": "col-sd-103",
            "summarizeBy": "sum"
          },
          {
            "name": "HRC_Night_RN",
            "dataType": "double",
            "sourceColumn": "HRC_Night_RN",
            "lineageTag": "col-sd-104",
            "summarizeBy": "sum"
          },
          {
            "name": "HRC_Night_LPN",
            "dataType": "double",
            "sourceColumn": "HRC_Night_LPN",
            "lineageTag": "col-sd-105",
            "summarizeBy": "sum"
          },
          {
            "name": "HRC_Night_Tech",
            "dataType": "double",
            "sourceColumn": "HRC_Night_Tech",
            "lineageTag": "col-sd-106",
            "summarizeBy": "sum"
          },
          {
            "name": "HRC_ShiftTotal",
            "dataType": "double",
            "sourceColumn": "HRC_ShiftTotal",
            "lineageTag": "col-sd-107",
            "summarizeBy": "sum"
          },
          {
            "name": "HRC_Ratio_Day",
            "dataType": "double",
            "sourceColumn": "HRC_Ratio_Day",
            "lineageTag": "col-sd-108",
            "summarizeBy": "sum"
          },
          {
            "name": "HRC_Ratio_Eve",
            "dataType": "double",
            "sourceColumn": "HRC_Ratio_Eve",
            "lineageTag": "col-sd-109",
            "summarizeBy": "sum"
          },
          {
            "name": "HRC_Ratio_Night",
            "dataType": "double",
            "sourceColumn": "HRC_Ratio_Night",
            "lineageTag": "col-sd-110",
            "summarizeBy": "sum"
          },
          {
            "name": "Total_RN",
            "dataType": "double",
            "sourceColumn": "Total_RN",
            "lineageTag": "col-sd-111",
            "summarizeBy": "sum"
          },
          {
            "name": "Total_LPN",
            "dataType": "double",
            "sourceColumn": "Total_LPN",
            "lineageTag": "col-sd-112",
            "summarizeBy": "sum"
          },
          {
            "name": "Total_Tech",
            "dataType": "double",
            "sourceColumn": "Total_Tech",
            "lineageTag": "col-sd-113",
            "summarizeBy": "sum"
          },
          {
            "name": "Total_ShiftStaff",
            "dataType": "double",
            "sourceColumn": "Total_ShiftStaff",
            "lineageTag": "col-sd-114",
            "summarizeBy": "sum"
          },
          {
            "name": "StaffPerShift",
            "dataType": "double",
            "sourceColumn": "StaffPerShift",
            "lineageTag": "col-sd-115",
            "summarizeBy": "sum"
          },
          {
            "name": "FloatShiftPositions",
            "dataType": "double",
            "sourceColumn": "FloatShiftPositions",
            "lineageTag": "col-sd-116",
            "summarizeBy": "sum"
          },
          {
            "name": "RN_ProdFTE",
            "dataType": "double",
            "sourceColumn": "RN_ProdFTE",
            "lineageTag": "col-sd-117",
            "summarizeBy": "sum"
          },
          {
            "name": "RN_AdjFTE",
            "dataType": "double",
            "sourceColumn": "RN_AdjFTE",
            "lineageTag": "col-sd-118",
            "summarizeBy": "sum"
          },
          {
            "name": "LPN_ProdFTE",
            "dataType": "double",
            "sourceColumn": "LPN_ProdFTE",
            "lineageTag": "col-sd-119",
            "summarizeBy": "sum"
          },
          {
            "name": "LPN_AdjFTE",
            "dataType": "double",
            "sourceColumn": "LPN_AdjFTE",
            "lineageTag": "col-sd-120",
            "summarizeBy": "sum"
          },
          {
            "name": "Tech_ProdFTE",
            "dataType": "double",
            "sourceColumn": "Tech_ProdFTE",
            "lineageTag": "col-sd-121",
            "summarizeBy": "sum"
          },
          {
            "name": "Tech_AdjFTE",
            "dataType": "double",
            "sourceColumn": "Tech_AdjFTE",
            "lineageTag": "col-sd-122",
            "summarizeBy": "sum"
          },
          {
            "name": "Float_ProdFTE",
            "dataType": "double",
            "sourceColumn": "Float_ProdFTE",
            "lineageTag": "col-sd-123",
            "summarizeBy": "sum"
          },
          {
            "name": "Float_AdjFTE",
            "dataType": "double",
            "sourceColumn": "Float_AdjFTE",
            "lineageTag": "col-sd-124",
            "summarizeBy": "sum"
          },
          {
            "name": "OneOne_ProdFTE",
            "dataType": "double",
            "sourceColumn": "OneOne_ProdFTE",
            "lineageTag": "col-sd-125",
            "summarizeBy": "sum"
          },
          {
            "name": "OneOne_AdjFTE",
            "dataType": "double",
            "sourceColumn": "OneOne_AdjFTE",
            "lineageTag": "col-sd-126",
            "summarizeBy": "sum"
          },
          {
            "name": "VarProdFTE",
            "dataType": "double",
            "sourceColumn": "VarProdFTE",
            "lineageTag": "col-sd-127",
            "summarizeBy": "sum"
          },
          {
            "name": "VarAdjFTE",
            "dataType": "double",
            "sourceColumn": "VarAdjFTE",
            "lineageTag": "col-sd-128",
            "summarizeBy": "sum"
          },
          {
            "name": "VarNP_Add",
            "dataType": "double",
            "sourceColumn": "VarNP_Add",
            "lineageTag": "col-sd-129",
            "summarizeBy": "sum"
          },
          {
            "name": "FixedFTE",
            "dataType": "double",
            "sourceColumn": "FixedFTE",
            "lineageTag": "col-sd-130",
            "summarizeBy": "sum"
          },
          {
            "name": "FixedHC",
            "dataType": "double",
            "sourceColumn": "FixedHC",
            "lineageTag": "col-sd-131",
            "summarizeBy": "sum"
          },
          {
            "name": "FixedSource",
            "dataType": "string",
            "sourceColumn": "FixedSource",
            "lineageTag": "col-sd-132",
            "summarizeBy": "none"
          },
          {
            "name": "GrandProdFTE",
            "dataType": "double",
            "sourceColumn": "GrandProdFTE",
            "lineageTag": "col-sd-133",
            "summarizeBy": "sum"
          },
          {
            "name": "GrandAdjFTE",
            "dataType": "double",
            "sourceColumn": "GrandAdjFTE",
            "lineageTag": "col-sd-134",
            "summarizeBy": "sum"
          },
          {
            "name": "EPOB_DirectCare",
            "dataType": "double",
            "sourceColumn": "EPOB_DirectCare",
            "lineageTag": "col-sd-135",
            "summarizeBy": "none"
          },
          {
            "name": "EPOB_TotalFacility",
            "dataType": "double",
            "sourceColumn": "EPOB_TotalFacility",
            "lineageTag": "col-sd-136",
            "summarizeBy": "none"
          },
          {
            "name": "EPOB_Productive",
            "dataType": "double",
            "sourceColumn": "EPOB_Productive",
            "lineageTag": "col-sd-137",
            "summarizeBy": "none"
          },
          {
            "name": "EPOB_VarPerPatient",
            "dataType": "double",
            "sourceColumn": "EPOB_VarPerPatient",
            "lineageTag": "col-sd-138",
            "summarizeBy": "none"
          },
          {
            "name": "EPOB_FixPerPatient",
            "dataType": "double",
            "sourceColumn": "EPOB_FixPerPatient",
            "lineageTag": "col-sd-139",
            "summarizeBy": "none"
          },
          {
            "name": "HasPayrollData",
            "dataType": "boolean",
            "sourceColumn": "HasPayrollData",
            "lineageTag": "col-sd-140",
            "summarizeBy": "none"
          },
          {
            "name": "PayrollFileName",
            "dataType": "string",
            "sourceColumn": "PayrollFileName",
            "lineageTag": "col-sd-141",
            "summarizeBy": "none"
          },
          {
            "name": "PayrollDayCount",
            "dataType": "double",
            "sourceColumn": "PayrollDayCount",
            "lineageTag": "col-sd-142",
            "summarizeBy": "sum"
          },
          {
            "name": "PayrollStartDate",
            "dataType": "string",
            "sourceColumn": "PayrollStartDate",
            "lineageTag": "col-sd-143",
            "summarizeBy": "none"
          },
          {
            "name": "PayrollEndDate",
            "dataType": "string",
            "sourceColumn": "PayrollEndDate",
            "lineageTag": "col-sd-144",
            "summarizeBy": "none"
          },
          {
            "name": "Actual_HrsDay_1East",
            "dataType": "double",
            "sourceColumn": "Actual_HrsDay_1East",
            "lineageTag": "col-sd-145",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_HC_1East",
            "dataType": "double",
            "sourceColumn": "Actual_HC_1East",
            "lineageTag": "col-sd-146",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_OT_1East",
            "dataType": "double",
            "sourceColumn": "Actual_OT_1East",
            "lineageTag": "col-sd-147",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_NpHrs_1East",
            "dataType": "double",
            "sourceColumn": "Actual_NpHrs_1East",
            "lineageTag": "col-sd-148",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_Wages_1East",
            "dataType": "double",
            "sourceColumn": "Actual_Wages_1East",
            "lineageTag": "col-sd-149",
            "summarizeBy": "sum"
          },
          {
            "name": "Model_HrsDay_1East",
            "dataType": "double",
            "sourceColumn": "Model_HrsDay_1East",
            "lineageTag": "col-sd-150",
            "summarizeBy": "sum"
          },
          {
            "name": "Variance_HrsDay_1East",
            "dataType": "double",
            "sourceColumn": "Variance_HrsDay_1East",
            "lineageTag": "col-sd-151",
            "summarizeBy": "sum"
          },
          {
            "name": "Variance_Pct_1East",
            "dataType": "double",
            "sourceColumn": "Variance_Pct_1East",
            "lineageTag": "col-sd-152",
            "summarizeBy": "none"
          },
          {
            "name": "Actual_HrsDay_2East",
            "dataType": "double",
            "sourceColumn": "Actual_HrsDay_2East",
            "lineageTag": "col-sd-153",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_HC_2East",
            "dataType": "double",
            "sourceColumn": "Actual_HC_2East",
            "lineageTag": "col-sd-154",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_OT_2East",
            "dataType": "double",
            "sourceColumn": "Actual_OT_2East",
            "lineageTag": "col-sd-155",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_NpHrs_2East",
            "dataType": "double",
            "sourceColumn": "Actual_NpHrs_2East",
            "lineageTag": "col-sd-156",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_Wages_2East",
            "dataType": "double",
            "sourceColumn": "Actual_Wages_2East",
            "lineageTag": "col-sd-157",
            "summarizeBy": "sum"
          },
          {
            "name": "Model_HrsDay_2East",
            "dataType": "double",
            "sourceColumn": "Model_HrsDay_2East",
            "lineageTag": "col-sd-158",
            "summarizeBy": "sum"
          },
          {
            "name": "Variance_HrsDay_2East",
            "dataType": "double",
            "sourceColumn": "Variance_HrsDay_2East",
            "lineageTag": "col-sd-159",
            "summarizeBy": "sum"
          },
          {
            "name": "Variance_Pct_2East",
            "dataType": "double",
            "sourceColumn": "Variance_Pct_2East",
            "lineageTag": "col-sd-160",
            "summarizeBy": "none"
          },
          {
            "name": "Actual_HrsDay_2West",
            "dataType": "double",
            "sourceColumn": "Actual_HrsDay_2West",
            "lineageTag": "col-sd-161",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_HC_2West",
            "dataType": "double",
            "sourceColumn": "Actual_HC_2West",
            "lineageTag": "col-sd-162",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_OT_2West",
            "dataType": "double",
            "sourceColumn": "Actual_OT_2West",
            "lineageTag": "col-sd-163",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_NpHrs_2West",
            "dataType": "double",
            "sourceColumn": "Actual_NpHrs_2West",
            "lineageTag": "col-sd-164",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_Wages_2West",
            "dataType": "double",
            "sourceColumn": "Actual_Wages_2West",
            "lineageTag": "col-sd-165",
            "summarizeBy": "sum"
          },
          {
            "name": "Model_HrsDay_2West",
            "dataType": "double",
            "sourceColumn": "Model_HrsDay_2West",
            "lineageTag": "col-sd-166",
            "summarizeBy": "sum"
          },
          {
            "name": "Variance_HrsDay_2West",
            "dataType": "double",
            "sourceColumn": "Variance_HrsDay_2West",
            "lineageTag": "col-sd-167",
            "summarizeBy": "sum"
          },
          {
            "name": "Variance_Pct_2West",
            "dataType": "double",
            "sourceColumn": "Variance_Pct_2West",
            "lineageTag": "col-sd-168",
            "summarizeBy": "none"
          },
          {
            "name": "Actual_HrsDay_3East",
            "dataType": "double",
            "sourceColumn": "Actual_HrsDay_3East",
            "lineageTag": "col-sd-169",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_HC_3East",
            "dataType": "double",
            "sourceColumn": "Actual_HC_3East",
            "lineageTag": "col-sd-170",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_OT_3East",
            "dataType": "double",
            "sourceColumn": "Actual_OT_3East",
            "lineageTag": "col-sd-171",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_NpHrs_3East",
            "dataType": "double",
            "sourceColumn": "Actual_NpHrs_3East",
            "lineageTag": "col-sd-172",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_Wages_3East",
            "dataType": "double",
            "sourceColumn": "Actual_Wages_3East",
            "lineageTag": "col-sd-173",
            "summarizeBy": "sum"
          },
          {
            "name": "Model_HrsDay_3East",
            "dataType": "double",
            "sourceColumn": "Model_HrsDay_3East",
            "lineageTag": "col-sd-174",
            "summarizeBy": "sum"
          },
          {
            "name": "Variance_HrsDay_3East",
            "dataType": "double",
            "sourceColumn": "Variance_HrsDay_3East",
            "lineageTag": "col-sd-175",
            "summarizeBy": "sum"
          },
          {
            "name": "Variance_Pct_3East",
            "dataType": "double",
            "sourceColumn": "Variance_Pct_3East",
            "lineageTag": "col-sd-176",
            "summarizeBy": "none"
          },
          {
            "name": "Actual_HrsDay_3West",
            "dataType": "double",
            "sourceColumn": "Actual_HrsDay_3West",
            "lineageTag": "col-sd-177",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_HC_3West",
            "dataType": "double",
            "sourceColumn": "Actual_HC_3West",
            "lineageTag": "col-sd-178",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_OT_3West",
            "dataType": "double",
            "sourceColumn": "Actual_OT_3West",
            "lineageTag": "col-sd-179",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_NpHrs_3West",
            "dataType": "double",
            "sourceColumn": "Actual_NpHrs_3West",
            "lineageTag": "col-sd-180",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_Wages_3West",
            "dataType": "double",
            "sourceColumn": "Actual_Wages_3West",
            "lineageTag": "col-sd-181",
            "summarizeBy": "sum"
          },
          {
            "name": "Model_HrsDay_3West",
            "dataType": "double",
            "sourceColumn": "Model_HrsDay_3West",
            "lineageTag": "col-sd-182",
            "summarizeBy": "sum"
          },
          {
            "name": "Variance_HrsDay_3West",
            "dataType": "double",
            "sourceColumn": "Variance_HrsDay_3West",
            "lineageTag": "col-sd-183",
            "summarizeBy": "sum"
          },
          {
            "name": "Variance_Pct_3West",
            "dataType": "double",
            "sourceColumn": "Variance_Pct_3West",
            "lineageTag": "col-sd-184",
            "summarizeBy": "none"
          },
          {
            "name": "Actual_HrsDay_HRC",
            "dataType": "double",
            "sourceColumn": "Actual_HrsDay_HRC",
            "lineageTag": "col-sd-185",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_HC_HRC",
            "dataType": "double",
            "sourceColumn": "Actual_HC_HRC",
            "lineageTag": "col-sd-186",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_OT_HRC",
            "dataType": "double",
            "sourceColumn": "Actual_OT_HRC",
            "lineageTag": "col-sd-187",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_NpHrs_HRC",
            "dataType": "double",
            "sourceColumn": "Actual_NpHrs_HRC",
            "lineageTag": "col-sd-188",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_Wages_HRC",
            "dataType": "double",
            "sourceColumn": "Actual_Wages_HRC",
            "lineageTag": "col-sd-189",
            "summarizeBy": "sum"
          },
          {
            "name": "Model_HrsDay_HRC",
            "dataType": "double",
            "sourceColumn": "Model_HrsDay_HRC",
            "lineageTag": "col-sd-190",
            "summarizeBy": "sum"
          },
          {
            "name": "Variance_HrsDay_HRC",
            "dataType": "double",
            "sourceColumn": "Variance_HrsDay_HRC",
            "lineageTag": "col-sd-191",
            "summarizeBy": "sum"
          },
          {
            "name": "Variance_Pct_HRC",
            "dataType": "double",
            "sourceColumn": "Variance_Pct_HRC",
            "lineageTag": "col-sd-192",
            "summarizeBy": "none"
          },
          {
            "name": "Actual_VarHrsDay_Total",
            "dataType": "double",
            "sourceColumn": "Actual_VarHrsDay_Total",
            "lineageTag": "col-sd-193",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_FixHrsDay_Total",
            "dataType": "double",
            "sourceColumn": "Actual_FixHrsDay_Total",
            "lineageTag": "col-sd-194",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_VarHC_Total",
            "dataType": "double",
            "sourceColumn": "Actual_VarHC_Total",
            "lineageTag": "col-sd-195",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_FixHC_Total",
            "dataType": "double",
            "sourceColumn": "Actual_FixHC_Total",
            "lineageTag": "col-sd-196",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_OT_Total",
            "dataType": "double",
            "sourceColumn": "Actual_OT_Total",
            "lineageTag": "col-sd-197",
            "summarizeBy": "sum"
          },
          {
            "name": "Model_VarHrsDay_Total",
            "dataType": "double",
            "sourceColumn": "Model_VarHrsDay_Total",
            "lineageTag": "col-sd-198",
            "summarizeBy": "sum"
          },
          {
            "name": "Variance_VarHrsDay_Total",
            "dataType": "double",
            "sourceColumn": "Variance_VarHrsDay_Total",
            "lineageTag": "col-sd-199",
            "summarizeBy": "sum"
          },
          {
            "name": "Variance_VarPct_Total",
            "dataType": "double",
            "sourceColumn": "Variance_VarPct_Total",
            "lineageTag": "col-sd-200",
            "summarizeBy": "none"
          },
          {
            "name": "Actual_VarFTE",
            "dataType": "double",
            "sourceColumn": "Actual_VarFTE",
            "lineageTag": "col-sd-201",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_FixFTE",
            "dataType": "double",
            "sourceColumn": "Actual_FixFTE",
            "lineageTag": "col-sd-202",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_TotalFTE",
            "dataType": "double",
            "sourceColumn": "Actual_TotalFTE",
            "lineageTag": "col-sd-203",
            "summarizeBy": "sum"
          },
          {
            "name": "Actual_EPOB_DC",
            "dataType": "double",
            "sourceColumn": "Actual_EPOB_DC",
            "lineageTag": "col-sd-204",
            "summarizeBy": "none"
          },
          {
            "name": "Actual_EPOB_Total",
            "dataType": "double",
            "sourceColumn": "Actual_EPOB_Total",
            "lineageTag": "col-sd-205",
            "summarizeBy": "none"
          },
          {
            "name": "EPOB_DC_Variance",
            "dataType": "double",
            "sourceColumn": "EPOB_DC_Variance",
            "lineageTag": "col-sd-206",
            "summarizeBy": "none"
          },
          {
            "name": "EPOB_Total_Variance",
            "dataType": "double",
            "sourceColumn": "EPOB_Total_Variance",
            "lineageTag": "col-sd-207",
            "summarizeBy": "none"
          },
          {
            "name": "DateKey",
            "dataType": "dateTime",
            "lineageTag": "col-sd-datekey",
            "summarizeBy": "none",
            "type": "calculated",
            "expression": "DATE(YEAR(DATEVALUE([Date])), MONTH(DATEVALUE([Date])), DAY(DATEVALUE([Date])))"
          }
        ],
        "measures": [
          {
            "name": "Total Census",
            "expression": "SUM(StaffingData[TotalCensus])",
            "lineageTag": "msr-0",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "#,0",
            "displayFolder": "Core Metrics"
          },
          {
            "name": "Occupancy %",
            "expression": "DIVIDE(SUM(StaffingData[TotalCensus]), SUM(StaffingData[TotalStaffedBeds]), 0) * 100",
            "lineageTag": "msr-1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0\"%\"",
            "displayFolder": "Core Metrics"
          },
          {
            "name": "Census 1East",
            "expression": "SUM(StaffingData[Census_1East])",
            "lineageTag": "msr-2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "#,0",
            "displayFolder": "Census by Unit"
          },
          {
            "name": "Census 2East",
            "expression": "SUM(StaffingData[Census_2East])",
            "lineageTag": "msr-3",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "#,0",
            "displayFolder": "Census by Unit"
          },
          {
            "name": "Census 2West",
            "expression": "SUM(StaffingData[Census_2West])",
            "lineageTag": "msr-4",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "#,0",
            "displayFolder": "Census by Unit"
          },
          {
            "name": "Census 3East",
            "expression": "SUM(StaffingData[Census_3East])",
            "lineageTag": "msr-5",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "#,0",
            "displayFolder": "Census by Unit"
          },
          {
            "name": "Census 3West",
            "expression": "SUM(StaffingData[Census_3West])",
            "lineageTag": "msr-6",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "#,0",
            "displayFolder": "Census by Unit"
          },
          {
            "name": "Census HRC",
            "expression": "SUM(StaffingData[Census_HRC])",
            "lineageTag": "msr-7",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "#,0",
            "displayFolder": "Census by Unit"
          },
          {
            "name": "Total RN",
            "expression": "SUM(StaffingData[Total_RN])",
            "lineageTag": "msr-8",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "#,0",
            "displayFolder": "Core Metrics"
          },
          {
            "name": "Total LPN",
            "expression": "SUM(StaffingData[Total_LPN])",
            "lineageTag": "msr-9",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "#,0",
            "displayFolder": "Core Metrics"
          },
          {
            "name": "Total Tech",
            "expression": "SUM(StaffingData[Total_Tech])",
            "lineageTag": "msr-10",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "#,0",
            "displayFolder": "Core Metrics"
          },
          {
            "name": "Total Shift Staff",
            "expression": "SUM(StaffingData[Total_ShiftStaff])",
            "lineageTag": "msr-11",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "#,0",
            "displayFolder": "Core Metrics"
          },
          {
            "name": "DC EPOB",
            "expression": "AVERAGE(StaffingData[EPOB_DirectCare])",
            "lineageTag": "msr-12",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.00",
            "displayFolder": "Core Metrics"
          },
          {
            "name": "Total EPOB",
            "expression": "AVERAGE(StaffingData[EPOB_TotalFacility])",
            "lineageTag": "msr-13",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.00",
            "displayFolder": "Core Metrics"
          },
          {
            "name": "Variable FTE",
            "expression": "SUM(StaffingData[VarAdjFTE])",
            "lineageTag": "msr-14",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "FTE"
          },
          {
            "name": "Fixed FTE",
            "expression": "SUM(StaffingData[FixedFTE])",
            "lineageTag": "msr-15",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "FTE"
          },
          {
            "name": "Grand Total FTE",
            "expression": "SUM(StaffingData[GrandAdjFTE])",
            "lineageTag": "msr-16",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "FTE"
          },
          {
            "name": "RN Adj FTE",
            "expression": "SUM(StaffingData[RN_AdjFTE])",
            "lineageTag": "msr-17",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "FTE"
          },
          {
            "name": "LPN Adj FTE",
            "expression": "SUM(StaffingData[LPN_AdjFTE])",
            "lineageTag": "msr-18",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "FTE"
          },
          {
            "name": "Tech Adj FTE",
            "expression": "SUM(StaffingData[Tech_AdjFTE])",
            "lineageTag": "msr-19",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "FTE"
          },
          {
            "name": "OT Hours Total",
            "expression": "SUM(StaffingData[Actual_OT_Total])",
            "lineageTag": "msr-20",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "Payroll Variance"
          },
          {
            "name": "Hours Variance",
            "expression": "SUM(StaffingData[Variance_VarHrsDay_Total])",
            "lineageTag": "msr-21",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "Payroll Variance"
          },
          {
            "name": "Variance %",
            "expression": "AVERAGE(StaffingData[Variance_VarPct_Total])",
            "lineageTag": "msr-22",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0\"%\"",
            "displayFolder": "Payroll Variance"
          },
          {
            "name": "Actual Daily Hours",
            "expression": "SUM(StaffingData[Actual_VarHrsDay_Total])",
            "lineageTag": "msr-23",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "Payroll Variance"
          },
          {
            "name": "Model Daily Hours",
            "expression": "SUM(StaffingData[Model_VarHrsDay_Total])",
            "lineageTag": "msr-24",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "Payroll Variance"
          },
          {
            "name": "NP Model %",
            "expression": "AVERAGE(StaffingData[NP_ModelPct])",
            "lineageTag": "msr-25",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0\"%\"",
            "displayFolder": "Core Metrics"
          },
          {
            "name": "Observation Hours",
            "expression": "SUM(StaffingData[ObsHrs_Total])",
            "lineageTag": "msr-26",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "Core Metrics"
          },
          {
            "name": "MTD Avg Daily Census",
            "expression": "VAR _today = TODAY() VAR _monthStart = DATE(YEAR(_today), MONTH(_today), 1) RETURN CALCULATE(AVERAGE(StaffingData[TotalCensus]), DateTable[Date] >= _monthStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-27",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "MTD Metrics"
          },
          {
            "name": "MTD Avg Census 1East",
            "expression": "VAR _today = TODAY() VAR _monthStart = DATE(YEAR(_today), MONTH(_today), 1) RETURN CALCULATE(AVERAGE(StaffingData[Census_1East]), DateTable[Date] >= _monthStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-28",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "MTD Metrics"
          },
          {
            "name": "MTD Avg Census 2East",
            "expression": "VAR _today = TODAY() VAR _monthStart = DATE(YEAR(_today), MONTH(_today), 1) RETURN CALCULATE(AVERAGE(StaffingData[Census_2East]), DateTable[Date] >= _monthStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-29",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "MTD Metrics"
          },
          {
            "name": "MTD Avg Census 2West",
            "expression": "VAR _today = TODAY() VAR _monthStart = DATE(YEAR(_today), MONTH(_today), 1) RETURN CALCULATE(AVERAGE(StaffingData[Census_2West]), DateTable[Date] >= _monthStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-30",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "MTD Metrics"
          },
          {
            "name": "MTD Avg Census 3East",
            "expression": "VAR _today = TODAY() VAR _monthStart = DATE(YEAR(_today), MONTH(_today), 1) RETURN CALCULATE(AVERAGE(StaffingData[Census_3East]), DateTable[Date] >= _monthStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-31",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "MTD Metrics"
          },
          {
            "name": "MTD Avg Census 3West",
            "expression": "VAR _today = TODAY() VAR _monthStart = DATE(YEAR(_today), MONTH(_today), 1) RETURN CALCULATE(AVERAGE(StaffingData[Census_3West]), DateTable[Date] >= _monthStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-32",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "MTD Metrics"
          },
          {
            "name": "MTD Avg Census HRC",
            "expression": "VAR _today = TODAY() VAR _monthStart = DATE(YEAR(_today), MONTH(_today), 1) RETURN CALCULATE(AVERAGE(StaffingData[Census_HRC]), DateTable[Date] >= _monthStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-33",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "MTD Metrics"
          },
          {
            "name": "MTD Avg Occupancy %",
            "expression": "DIVIDE([MTD Avg Daily Census], 114, 0) * 100",
            "lineageTag": "msr-34",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0\"%\"",
            "displayFolder": "MTD Metrics"
          },
          {
            "name": "MTD Avg DC EPOB",
            "expression": "VAR _today = TODAY() VAR _monthStart = DATE(YEAR(_today), MONTH(_today), 1) RETURN CALCULATE(AVERAGE(StaffingData[EPOB_DirectCare]), DateTable[Date] >= _monthStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-35",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.00",
            "displayFolder": "MTD Metrics"
          },
          {
            "name": "MTD Avg Total EPOB",
            "expression": "VAR _today = TODAY() VAR _monthStart = DATE(YEAR(_today), MONTH(_today), 1) RETURN CALCULATE(AVERAGE(StaffingData[EPOB_TotalFacility]), DateTable[Date] >= _monthStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-36",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.00",
            "displayFolder": "MTD Metrics"
          },
          {
            "name": "MTD Avg Variable FTE",
            "expression": "VAR _today = TODAY() VAR _monthStart = DATE(YEAR(_today), MONTH(_today), 1) RETURN CALCULATE(AVERAGE(StaffingData[VarAdjFTE]), DateTable[Date] >= _monthStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-37",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "MTD Metrics"
          },
          {
            "name": "MTD Avg Grand FTE",
            "expression": "VAR _today = TODAY() VAR _monthStart = DATE(YEAR(_today), MONTH(_today), 1) RETURN CALCULATE(AVERAGE(StaffingData[GrandAdjFTE]), DateTable[Date] >= _monthStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-38",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "MTD Metrics"
          },
          {
            "name": "MTD Total OT Hours",
            "expression": "VAR _today = TODAY() VAR _monthStart = DATE(YEAR(_today), MONTH(_today), 1) RETURN CALCULATE(SUM(StaffingData[Actual_OT_Total]), DateTable[Date] >= _monthStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-39",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "MTD Metrics"
          },
          {
            "name": "MTD Avg Hours Variance",
            "expression": "VAR _today = TODAY() VAR _monthStart = DATE(YEAR(_today), MONTH(_today), 1) RETURN CALCULATE(AVERAGE(StaffingData[Variance_VarHrsDay_Total]), DateTable[Date] >= _monthStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-40",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "MTD Metrics"
          },
          {
            "name": "MTD Days Count",
            "expression": "VAR _today = TODAY() VAR _monthStart = DATE(YEAR(_today), MONTH(_today), 1) RETURN CALCULATE(COUNTROWS(StaffingData), DateTable[Date] >= _monthStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-41",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "#,0",
            "displayFolder": "MTD Metrics"
          },
          {
            "name": "YTD Avg Daily Census",
            "expression": "VAR _today = TODAY() VAR _yearStart = DATE(YEAR(_today), 1, 1) RETURN CALCULATE(AVERAGE(StaffingData[TotalCensus]), DateTable[Date] >= _yearStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-42",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "YTD Metrics"
          },
          {
            "name": "YTD Avg Census 1East",
            "expression": "VAR _today = TODAY() VAR _yearStart = DATE(YEAR(_today), 1, 1) RETURN CALCULATE(AVERAGE(StaffingData[Census_1East]), DateTable[Date] >= _yearStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-43",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "YTD Metrics"
          },
          {
            "name": "YTD Avg Census 2East",
            "expression": "VAR _today = TODAY() VAR _yearStart = DATE(YEAR(_today), 1, 1) RETURN CALCULATE(AVERAGE(StaffingData[Census_2East]), DateTable[Date] >= _yearStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-44",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "YTD Metrics"
          },
          {
            "name": "YTD Avg Census 2West",
            "expression": "VAR _today = TODAY() VAR _yearStart = DATE(YEAR(_today), 1, 1) RETURN CALCULATE(AVERAGE(StaffingData[Census_2West]), DateTable[Date] >= _yearStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-45",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "YTD Metrics"
          },
          {
            "name": "YTD Avg Census 3East",
            "expression": "VAR _today = TODAY() VAR _yearStart = DATE(YEAR(_today), 1, 1) RETURN CALCULATE(AVERAGE(StaffingData[Census_3East]), DateTable[Date] >= _yearStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-46",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "YTD Metrics"
          },
          {
            "name": "YTD Avg Census 3West",
            "expression": "VAR _today = TODAY() VAR _yearStart = DATE(YEAR(_today), 1, 1) RETURN CALCULATE(AVERAGE(StaffingData[Census_3West]), DateTable[Date] >= _yearStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-47",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "YTD Metrics"
          },
          {
            "name": "YTD Avg Census HRC",
            "expression": "VAR _today = TODAY() VAR _yearStart = DATE(YEAR(_today), 1, 1) RETURN CALCULATE(AVERAGE(StaffingData[Census_HRC]), DateTable[Date] >= _yearStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-48",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "YTD Metrics"
          },
          {
            "name": "YTD Avg Occupancy %",
            "expression": "DIVIDE([YTD Avg Daily Census], 114, 0) * 100",
            "lineageTag": "msr-49",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0\"%\"",
            "displayFolder": "YTD Metrics"
          },
          {
            "name": "YTD Avg DC EPOB",
            "expression": "VAR _today = TODAY() VAR _yearStart = DATE(YEAR(_today), 1, 1) RETURN CALCULATE(AVERAGE(StaffingData[EPOB_DirectCare]), DateTable[Date] >= _yearStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-50",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.00",
            "displayFolder": "YTD Metrics"
          },
          {
            "name": "YTD Avg Total EPOB",
            "expression": "VAR _today = TODAY() VAR _yearStart = DATE(YEAR(_today), 1, 1) RETURN CALCULATE(AVERAGE(StaffingData[EPOB_TotalFacility]), DateTable[Date] >= _yearStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-51",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.00",
            "displayFolder": "YTD Metrics"
          },
          {
            "name": "YTD Avg Variable FTE",
            "expression": "VAR _today = TODAY() VAR _yearStart = DATE(YEAR(_today), 1, 1) RETURN CALCULATE(AVERAGE(StaffingData[VarAdjFTE]), DateTable[Date] >= _yearStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-52",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "YTD Metrics"
          },
          {
            "name": "YTD Avg Grand FTE",
            "expression": "VAR _today = TODAY() VAR _yearStart = DATE(YEAR(_today), 1, 1) RETURN CALCULATE(AVERAGE(StaffingData[GrandAdjFTE]), DateTable[Date] >= _yearStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-53",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "YTD Metrics"
          },
          {
            "name": "YTD Total OT Hours",
            "expression": "VAR _today = TODAY() VAR _yearStart = DATE(YEAR(_today), 1, 1) RETURN CALCULATE(SUM(StaffingData[Actual_OT_Total]), DateTable[Date] >= _yearStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-54",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "YTD Metrics"
          },
          {
            "name": "YTD Avg Hours Variance",
            "expression": "VAR _today = TODAY() VAR _yearStart = DATE(YEAR(_today), 1, 1) RETURN CALCULATE(AVERAGE(StaffingData[Variance_VarHrsDay_Total]), DateTable[Date] >= _yearStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-55",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "YTD Metrics"
          },
          {
            "name": "YTD Days Count",
            "expression": "VAR _today = TODAY() VAR _yearStart = DATE(YEAR(_today), 1, 1) RETURN CALCULATE(COUNTROWS(StaffingData), DateTable[Date] >= _yearStart && DateTable[Date] <= _today, ALL(DateTable))",
            "lineageTag": "msr-56",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "#,0",
            "displayFolder": "YTD Metrics"
          },
          {
            "name": "Prior Month Avg Census",
            "expression": "VAR _today = TODAY() VAR _priorMonthEnd = DATE(YEAR(_today), MONTH(_today), 1) - 1 VAR _priorMonthStart = DATE(YEAR(_priorMonthEnd), MONTH(_priorMonthEnd), 1) RETURN CALCULATE(AVERAGE(StaffingData[TotalCensus]), DateTable[Date] >= _priorMonthStart && DateTable[Date] <= _priorMonthEnd, ALL(DateTable))",
            "lineageTag": "msr-57",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.0",
            "displayFolder": "Comparisons"
          },
          {
            "name": "Census MTD vs Prior Month",
            "expression": "[MTD Avg Daily Census] - [Prior Month Avg Census]",
            "lineageTag": "msr-58",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "+0.0;-0.0;0.0",
            "displayFolder": "Comparisons"
          },
          {
            "name": "Census MTD vs Prior Month %",
            "expression": "DIVIDE([MTD Avg Daily Census] - [Prior Month Avg Census], [Prior Month Avg Census], 0) * 100",
            "lineageTag": "msr-59",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "+0.0\"%\";-0.0\"%\";0.0\"%\"",
            "displayFolder": "Comparisons"
          },
          {
            "name": "Actual vs Model FTE Variance",
            "expression": "SUM(StaffingData[Actual_TotalFTE]) - SUM(StaffingData[GrandAdjFTE])",
            "lineageTag": "msr-60",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "+0.0;-0.0;0.0",
            "displayFolder": "Comparisons"
          },
          {
            "name": "Actual DC EPOB",
            "expression": "AVERAGE(StaffingData[Actual_EPOB_DC])",
            "lineageTag": "msr-61",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.00",
            "displayFolder": "Payroll Variance"
          },
          {
            "name": "Actual Total EPOB",
            "expression": "AVERAGE(StaffingData[Actual_EPOB_Total])",
            "lineageTag": "msr-62",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "0.00",
            "displayFolder": "Payroll Variance"
          },
          {
            "name": "EPOB DC Variance",
            "expression": "AVERAGE(StaffingData[EPOB_DC_Variance])",
            "lineageTag": "msr-63",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "+0.00;-0.00;0.00",
            "displayFolder": "Payroll Variance"
          },
          {
            "name": "EPOB Total Variance",
            "expression": "AVERAGE(StaffingData[EPOB_Total_Variance])",
            "lineageTag": "msr-64",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\": true}"
              }
            ],
            "formatString": "+0.00;-0.00;0.00",
            "displayFolder": "Payroll Variance"
          }
        ]
      }
    ]
  }
}